### ISSUE TITLE
Memory downloads on AMD macOS are slow

### ISSUE THREAD

**Issue by matpaul** [gfx-rs/wgpu#1075]
**Description**
device.poll(wgpu::Maintain::Wait); takes a lot of time

**Repro steps**
In capture example change sizes to 2048, measure device.poll

**Expected vs observed behavior**
expected: should be ~ 4-5ms, 
observed: 12-16ms, sometimes >48ms

**Extra materials**
[metal_profile_last.trace.zip](https://github.com/gfx-rs/wgpu/files/5646103/metal_profile_last.trace.zip)

**Platform**
MacOS 10.15.6 (19G73), 2,3 GHz Intel Core i9, AMD Radeon Pro 5600M

**Comment by kvark** [comment]
<img width="1359" alt="Screen Shot 2020-12-04 at 18 47 53" src="https://user-images.githubusercontent.com/107301/101226979-42c88880-3664-11eb-99cd-9baef79b4743.png">

This is what AMD is doing:
  1. the driver spends a whole 2ms going through the command buffers, which pretty much do nothing
  2. then almost 1ms filling out the contents with zeroes
  3. then clearing takes 175us
  4. and then we spend 2.18ms invalidating the memory ranges... This one certainly can be better
  5. finally, to add insult to injury, the AMD driver takes a sweet 4.72ms freeing the memory back

We need to investigate why non-coherent memory is being used here, since it hurts us too much. cc @zakarumych

**Comment by zakarumych** [comment]
What usage flags are specified into allocator?
It prefers coherent memory for both UPLOAD and DOWNLOAD usage flags.
But it values more cached memory for DOWNLOADs. So if choice is either CACHED or COHERENT for DOWNLOAD it will pick CACHED.

**Comment by kvark** [comment]
Ok looks like it's [this type](https://github.com/gfx-rs/gfx/blob/5242890ddd9a2f112e68a9d599d9e79a532e31e9/src/backend/metal/src/device.rs#L217) being picked. I'll remove it from the backend.

**Comment by zakarumych** [comment]
It clearly was the type for downloads. Why do you think it will work better with another type?

**Comment by kvark** [comment]
> It clearly was the type for downloads

Metal doesn't define a type for downloads. It's what we used to define, but that was a mistake.
Non-coherent memory in Metal is invalidated through a command buffer (unlike Vulkan, where it's done through a device). And the Vulkan spec says that one can start CPU-accessing the memory contents right after it's invalidated (*), so our implementation currently submits a command buffer and waits for it, which is a perf disaster.
So currently it's best to just make the clients use the regular coherent memory for downloads, instead.

(*) technically there is an access transition from, say, buffer::Access::SHADER_WRITE, to buffer::Access::HOST_READ, and we should be inserting the invalidation there. Filed https://github.com/gfx-rs/gfx/issues/3515 to follow-up with that.

**Comment by kvark** [comment]
Btw, we picked up the gfx changes in #1071, closing.
