### ISSUE TITLE
DEVICE_LOST and visibility

### ISSUE THREAD

**Issue by baptistemanson** [gfx-rs/wgpu#1141]
This fragment shader:
```glsl
#version 450
layout(set = 0, binding = 0) uniform MainBlock {
    vec2 nb_tiles;
};
void main() {

}
```
triggers a DEVICE_LOST exception when the visibility is incorrectly set to wgpu::ShaderStage::VERTEX instead of wgpu::ShaderStage::FRAGMENT:
```rust
 wgpu::BindGroupLayoutEntry {
                    binding: 0, //
                    visibility: wgpu::ShaderStage::VERTEX,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None, // 2 floats?
                    },
                    count: None,
                },
```
This happens on current master 7e6bc07955ddbe8b519ee4bd76fad4bf2500ad5a of wgpu-rs.

The stack trace is here: https://gist.github.com/baptistemanson/23a2a1b2ad23845a6dd1e04ceab5b610

**Comment by kvark** [comment]
Thank you for filing!
Is this the whole shader, or are the details omitted? They are important here, since they could limit the ability of Naga to parse the shader. The exact one you provided should work, and I double-checked the validation code - we definitely have the check for the binding stages here - https://github.com/gfx-rs/wgpu/blob/5a29e010e2b8fb29c3edcc3dc9c8435517ac4497/wgpu-core/src/validation.rs#L819

The best way to provide us with a repro case is by recording an [API trace](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure) and attaching it (zipped) here.

**Comment by baptistemanson** [comment]
I will attach a trace tomorrow. Having too much fun with the api right now :).
Here is the shader in question:
```glsl
#version 450
precision highp float;
precision highp int;
layout(location = 0) in vec2 v_TexCoord;
layout(location = 0) out vec4 o_Target;
layout(set = 0, binding = 1) uniform texture2D t_tile;
layout(set = 0, binding = 2) uniform sampler s;
layout(set = 0, binding = 3) uniform texture2D t_tile_index;

layout(set = 0, binding = 0) uniform MainBlock {
    vec2 nb_tiles;
};

vec2 tile_dim = 1. / nb_tiles;

void main() {
    // tiling engine
    vec4 tile_index = texture(sampler2D(t_tile_index, s), v_TexCoord);
    float to_pick = tile_index.r*255.;
    vec2 tile_to_pick = vec2( mod(to_pick,nb_tiles.x), floor(to_pick/nb_tiles.y));
    vec2 inner_tile = mod(v_TexCoord.xy, tile_dim) + tile_to_pick * tile_dim;
    vec4 tex = texture(sampler2D(t_tile, s), inner_tile);
    o_Target = vec4(tex.rgb,1.0);
}
```
Ill try to bundle up a minimal example.

**Comment by kvark** [comment]
Thanks, we don't need any more info. Naga's SPIR-V parser was confused by the private variable you have (`vec2 tile_dim`). Fix is coming in https://github.com/gfx-rs/naga/pull/353
