### ISSUE TITLE
Tracing should be optional (especially in dependencies)

### ISSUE THREAD

**Issue by grovesNL** [gfx-rs/wgpu#1189]
**Is your feature request related to a problem? Please describe.**
`tracing` features are enabled unconditionally for some dependencies which can add performance overhead. It's also often used as debug feature and release builds might want to avoid it.

e.g. a crate downstream noticed a lot of overhead when tracing is enabled in gpu-alloc, but wgpu provides no way to opt out of this feature because it's always enabled: https://github.com/gfx-rs/wgpu/blob/8ed543f26a379a2d165f1592710e7f882a15b862/wgpu-core/Cargo.toml#L36-L37

Whether tracing is enabled or disabled can be controlled from the tracing crate's API, but downstream crates not interested in tracing probably shouldn't need to be aware of this.

**Describe the solution you'd like**
`tracing` probably shouldn't be unconditionally enabled. Maybe wgpu could forward the existing `tracing` feature, or possibly not enable it for dependencies at all.

We could also feature-gate tracing inside of wgpu's span macro or other places, e.g. use `#[cfg(feature = "tracing")]` to avoid creating tracing spans in https://github.com/gfx-rs/wgpu/blob/780637eec029097e37dff9238abca7248354b465/wgpu-core/src/lib.rs#L251

**Describe alternatives you've considered**
Downstream crates opting out of tracing by using the API in the `tracing` crate

**Additional context**
It was mentioned on Discord that significant amounts of time are spent in gpu-alloc's tracing and places like https://github.com/gfx-rs/wgpu/blob/f0556d7d8b05295956248d6384cffb76bdb12707/wgpu-core/src/command/render.rs#L2072

We might also want to consider making tracing optional in wgpu-rs for some of the same reasons above.

**Comment by Aeledfyr** [comment]
The four functions that had significant overhead due to tracing in my case were:
`wgpu_core::command::render::render_ffi::wgpu_render_pass_set_vertex_buffer`
`wgpu_core::command::render::render_ffi::wgpu_render_pass_draw_indexed`
`gpu_alloc::allocator::GpuAllocator<M>::alloc`
`gpu_alloc::allocator::GpuAllocator<M>::dealloc`

As mentioned, `gpu-alloc` has a feature to enable tracing debug info that's enabled by default in wgpu-core; moving that behind a feature flag in wgpu would be easy enough.

Most of the functions in `render_ffi` do very little work, and generally just push items onto `Vec`s.  Some of these are called thousands of times per frame, so the minor overhead of tracing's spans ends up taking a significant amount of time.  Since the durations of these functions are likely too small to measure with a span, tracing's events could work better, though that would cause inconsistencies with the rest of the tracing output.

A better solution would be to have the ability to disable the use of tracing for the API, and keep it only for logging.  If all of the API logging goes through the custom `span` macro, then that would be an easy way to disable it.

**Comment by kvark** [comment]
That's sad truth. When calling tracing, we expect it to be free unless the relevant log level is activated by the user.
One thing I'm confused about is - does `log::debug!` also have this overhead in release? My understanding was that it defines the cut-off logging level as a feature, so you don't get the overhead in release.

I think making it optional is a good direction. @grovesNL would you want to prototype that?

A more radical option could be to evaluate https://crates.io/crates/profiling . Could it be used to cover the needs we have in profiling? Would probably need to be combined with `log` use.

also summoning @cwfitzgerald

**Comment by kvark** [comment]
Why are we even logging/tracing the render pass commands? cc @cwfitzgerald 
For measuring the cost of encoding, the `render_pass_finish()` needs to be profiled, where the work actually happens.
For debugging, the API traces do a better job anyway.
