### ISSUE TITLE
bug: Invalid BindGroupLayout when using getBindGroupLayout from ComputePipeline

### ISSUE THREAD

**Issue by DjDeveloperr** [gfx-rs/wgpu#1264]
**Description**
I'm getting a BindGroupLayout with label `<Invalid-BindGroupLayout label=<derived>>` when calling `getBindGroupLayout` on `GPUComputePipeline`.

**Expected vs observed behavior**
It should create a valid BindGroupLayout without any such label. The same shader is tested on Chrome Canary and works fine (provides a valid BindGroupLayout).

**Extra materials**
[wgpu_trace.zip](https://github.com/gfx-rs/wgpu/files/6141802/wgpu_trace.zip)

**Platform**

![image](https://user-images.githubusercontent.com/43033058/111164096-b82ce900-85c3-11eb-9e82-7542ec31ef6d.png)

wgpu version: 0.7.0

**Comment by kvark** [comment]
I'm not able to replay the trace, unfortunately. This was fixed by #1245, which is not a part of `v0.7`.
I also tried to port `hello-compute` to use the implicit BGL, and it works fine. So this isn't a problem about compute vs render. It's rather the fact something went wrong with a particular shader you have. Could you attach the shader here, please?

**Comment by DjDeveloperr** [comment]
Here's the [shader](https://github.com/gfx-rs/wgpu/files/6146189/shader.txt) (GLSL, which was compiled to SPIR-V using Glslang)

**Comment by kvark** [comment]
Thank you! The problem here is that Naga fails to process the shader (because of the barrier instructions), and therefore its bindings are not reflected back to `wgpu`. Clearly, the error lacks this information.
I filed https://github.com/gfx-rs/naga/issues/583 to fix upstream.
In the meantime, I recommend providing the layout explicitly for this pipeline.

**Comment by DjDeveloperr** [comment]
[Another shader that has invalid bind group layout..](https://github.com/gfx-rs/wgpu/files/6170262/shader.txt)

Providing layout explicitly is not something I can do right now :/

**Comment by kvark** [comment]
This shader also uses control barriers.
@DjDeveloperr what's the reason for you to not specify the layout?

**Comment by DjDeveloperr** [comment]
I'm porting an [existing project](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-webgpu) with not much knowledge about shaders

**Comment by kvark** [comment]
I see. We'll try to prioritize getting barriers now. It's not going to be available till later next week though.

**Comment by DjDeveloperr** [comment]
Any update on this?

**Comment by kvark** [comment]
Sorry, we got sucked into other tasks :/
Thank you for pinging!

**Comment by DjDeveloperr** [comment]
Any ETA when this will be worked on?

**Comment by kvark** [comment]
Sorry about the delay! We got carried away with all the 0.8 release stuff.
Implementation for barriers is coming in https://github.com/gfx-rs/naga/pull/817

**Comment by DjDeveloperr** [comment]
This issue seems to be resolved (at least when using crate from GitHub). Thanks!
