### ISSUE TITLE
Procedural Macro to Precompile WGSL to SPIR-V

### ISSUE THREAD

**Issue by zer0x64** [gfx-rs/wgpu#1486]
**Is your feature request related to a problem? Please describe.**
I _might_ be missing something here, but AFAIK compiling SPIR-V to native GL should be faster than compiling from WGSL because of binary vs textual representation. Following Rust ideology, I think WGSL shaders should be precompiled at compile time to SPIR-V to make runtime shader compilation a tad faster and catch programming error at compile time.

**Describe the solution you'd like**
From what I've seen, writing a proc_macro (can be an external crate) that uses `naga` to compile the WGSL shaders to SPIR-V and include it embedded in the binary _should_ be pretty easy to do. 

**Additional context**
As stated above, I might be missing something and I might be completely wrong about this. If that's the case, can someone explain to me why parsing WGSL at runtime is better?

**Comment by cwfitzgerald** [comment]
Thanks for filing this!

So I don't believe this would be any faster because of the process that we use to translate shaders. We use our project [naga](https://github.com/gfx-rs/naga/) to do the translation. Both wgsl and spirv are parsed and turned into internal representation of your shader code. This IR is then validated and is then converted to the underlying shader languages. Because the validation and conversion is all input independent, there's no real advantage to one or the other. We believe our spirv and wgsl parser to be reasonably fast and shouldn't significantly affect performance. We should absolutely measure it, but wgsl is easy to parse and is designed to be easy to convert.

In addition, spirv is fairly verbose compared to shader languages so there isn't significant binary size between the representations.

Hope this answers some of your questions. If you have any more, please ask :)

**Comment by kvark** [comment]
@zer0x64 I think there is a bit of confusion here about how shader translation works:
> compiling SPIR-V to native GL should be faster than compiling from WGSL

Are you targeting native GL? We aren't doing SPIRV->GLSL, if that's what you are thinking. We aren't doing SPIRV->anything except Naga's intermediate representation (IR). Moreover, SPIRV->IR is quite complicated, it's one of the most bug-prone code paths in Naga because of how complex SPIRV is. WGSL->IR is the contrary - it's extremely smooth and fast.

So if you are concerned about performance, then just passing WGSL is the best. You can enable `profiling` backends in your app to see how much time exactly is spent in translation and validation of shades. We did some measurements in https://gfx-rs.github.io/2021/05/09/dota2-msl-compilation.html, and it turns out to be super fast with Naga.

**Comment by zer0x64** [comment]
Great! That answer my question!

The confusion was that I thought that SPIR-V -> IR was faster then WGSL -> IR because text is generally harder to parse then binary data.

One question however that still stands is compile-time validation. Right now, if there is an error in the WGSL code, the error will happen at runtime, which isn't very idiomatic for Rust. Of course, I think for safety that a runtime check is still required, but it might be a good idea to add an API like [include_wgsl](https://docs.rs/include_wgsl/1.0.0/include_wgsl/).

Of course, the macro for this already exists and can be used.

**Comment by kvark** [comment]
Validating WGSL at build time is something projects can already do. I don't think `include_wgsl` is solution that is universal enough to include in `wgpu::utils`, since it requires compiling the shader code in. It's annoying to rebuild your app every time something in the shaders change, and I think loading from files is better.

What we do for the WGSL examples is simply having a cargo test that looks for all the WGSL sources and compiles + validates them. See https://github.com/gfx-rs/wgpu/blob/master/wgpu/tests/example-wgsl.rs
If an application does something similar, it can also extend the test to do any preprocessing it needs.
If you think such code would be good to publish somewhere in a library, you are welcome to :)

Going to close the issue on this note, but please feel free to continue the discussion!

**Comment by zer0x64** [comment]
I like that idea of validating it in the tests! Well, thanks for the answers :)
