### ISSUE TITLE
Reintroduce being able to skip Naga parsing + validation.

### ISSUE THREAD

**Issue by ElectronicRU** [gfx-rs/wgpu#1520]
**Is your feature request related to a problem? Please describe.**
Naga's support for image ops is pretty lackluster - in particular, OpImage* can only reference global variables, which means access chains (ie things necessary to be able to do texture arrays) are completely unsupported. (And indeed, this makes sense, as upstream WGSL standard doesn't support them, too).

**Describe the solution you'd like**
Previously, you were able to bypass Naga if the backend understood SPIR-V. It'd be nice if we could provide backend-specific SPIR-V (or MSL for Metal, I guess?) for features not supported by WGSL yet again.

**Describe alternatives you've considered**
The alternative would be to push for inclusion of arrayed resource access in WGSL, which is a much more slow and laborious process. Hopefully once the standard and Naga is there, the workaround can be deleted, but right now, it'd be nice to have one.

**Comment by kvark** [comment]
> OpImage* can only reference global variables

This definitely needs to be fixed, and the sooner the better. WGSL is about to allow passing textures to functions as parameters.

> It'd be nice if we could provide backend-specific SPIR-V (or MSL for Metal, I guess?) for features not supported by WGSL yet again.

That's an interesting idea. Providing anything other than SPIR-V wouldn't be feasible, because the binding model is different between WebGPU and MSL. But SPIR-V should mostly work, and that's how you used it originally.

So this could be a native-only feature, I guess, and it will be unsafe. I.e. there would be a separate entry point for shader creation.

> The alternative would be to push for inclusion of arrayed resource access in WGSL, which is a much more slow and laborious process.

We don't need the spec changes right now in order to play with array resources. We can roll it out in the way we find reasonable, and that will help the specification to form.

**Comment by ElectronicRU** [comment]
In favor of making this unsafe, sounds good. Re: Naga fixes, I'm one of those people who are trying to use rust-gpu, and "features that are necessary to make rust-gpu work" - "features that are a priority for naga to support" are going to stay a non-empty set for a long time, I reckon :).
