### ISSUE TITLE
Repository Tags for Crates.io Releases

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/wgpu#1638]
It would be convenient to have GitHub tags corresponding to the `wgpu` crates.io releases. I just ran into the need while wanting to checkout the git commit that corresponded to wgpu 0.9.0. Since `wgpu-rs` is not the only thing in this repo, we would probably want  to differentiate the tags with a prefix or something like that. So the tag could be `wgpu-rs-v0.9.0` or something.

**Comment by cwfitzgerald** [comment]
We do have branches for each release, so you should be able to use those, though if tags would also be useful, that's a possibility too.

**Comment by zicklag** [comment]
The branches are great, but they also receive updates after releases that will go into later bugfix releases ( if I understand correctly ) so it's harder to know that you've gotten a certain release exactly. Like with the 0.9 branch being 12 commits ahead of master makes me think that it's gotten updates that haven't been released yet that might go into an 0.9.1 release or something?

It's not really that big of a deal, but if it wasn't hard to do it's a nice-to-have.

**Comment by cwfitzgerald** [comment]
Alright, I can go through and add tags for our releases.

**Comment by Gordon-F** [comment]
Maybe it would be better to publish new versions by CI ?

https://github.com/rust-windowing/winit/blob/master/.github/workflows/publish.yml

**Comment by cwfitzgerald** [comment]
Now that the family reunion has happened, fully automated publishing is definitely possible. I have a script that works really well for other projects, it would just need to be adapted here. I have held off on it as there were more important things to do and we don't actually release that often.

**Comment by kvark** [comment]
I still don't understand what would tags give you over branches for breaking revisions. At what point do you need to know the exact changes between 0.9.1 and 0.9.2? You can look for them based on the commits in 0.9 branch that correspond to version bumps, for example.

**Comment by zicklag** [comment]
Part of it was just intuition. I tend to look in the releases/tags list for the crates releases, and I didn't initially realize there was a branch there.

It's honestly probably not that big of a deal being that we already have branches.

My motivation is when I have the git source repo because I'm working on `master`, and I've got a project like bevy hooked up with a `patch` so that it uses my local `wgpu`, and then I want to quickly test out how what I'm working on compares to the previous released version that Bevy was already using from crates.io. But if I checkout the `v0.9` branch, then I'll potentially get unreleased commits, so it might not be exactly the same.

**Comment by kvark** [comment]
Ok, I see. We never have unreleased commits in the release branches. We back-port things in bursts, and each burst ends up with a release.

**Comment by erictapen** [comment]
I'm currently packaging wgpu-info for [Nixpkgs](https://github.com/NixOS/Nixpkgs) and for that, I need exact revisions, as we put a hash of the source repo alongside the build instructions.

From a package maintainer perspective it is kind of inconvenient to rely on commit ids here, as they don't tell the version they are from. Also it's not trivial to find the commit id corresponding to a particular release. Currently I'm even unable to find out which commit id corresponds to the `0.10.2` version published at [crates.io](https://crates.io/crates/wgpu/versions).

So git tags would help me a lot here.

**Comment by kvark** [comment]
> Ok, I see. We never have unreleased commits in the release branches. We back-port things in bursts, and each burst ends up with a release.

Actually, this was wrong. Sometimes we do have unreleased commits in the branches. Sometimes we release some of the crates, but not all of them. And that could be a part of the problem.

This repository contains the following crates: `wgpu-core`, `wgpu-hal`, `wgpu-types`, `wgpu`, and a few binary crates that are not published but nevertheless versioned, which affects @erictapen workflow. Does this workflow really care about when, say, wgpu-hal-0.10.4 was published?

Let's find out what exactly kind of versioning you need. I'm particularly curious because `wgpu-info` is a binary target. So it depends on the whole tree of dependencies, not just wgpu stuff. The only way for the build to be reproducible is to include the lockfile. There is one in 0.10 branch, but there isn't one in master any more.
So, technically speaking, the revision of that lockfile is what determines reproducible builds for wgpu-info, not any kind of tags we could add.

**Comment by erictapen** [comment]
Mh yeah reproducibililty is only aquired when the lockfile is in tree. Do you plan to continue without a Cargo.lock or will it be added for future release branches?

For the foreseeable future Nixpkgs won't contain pure Rust libraries, we only package applications (in this case `wgpu-info` and maybe eventually `player`). So best case for me would be having crate specific git tags for `wgpu-info` releases, e.g. `wgpu-info_0.10.0`. These tags should also contain a `Cargo.lock` file that locks the dependencies for those binaries. The alternative to having the lockfile in tree would be for me to manually generate one for each release and check that into Nixpkgs. But that's cumbersome and error prone, as I'd hit incompabilities between crate versions that didn't exist at the time of the release (and also we try to avoid adding such large files to Nixpkgs).

All the other crates wouldn't need git tags for my workflow to work out.

**Comment by kvark** [comment]
> Mh yeah reproducibililty is only aquired when the lockfile is in tree. Do you plan to continue without a Cargo.lock or will it be added for future release branches?

Filed #2017 to bring back the lockfile. We had to temporarily remove it, but the reason doesn't hold any more.

> So best case for me would be having crate specific git tags for wgpu-info releases, e.g. wgpu-info_0.10.0

There is a bit of a problem here - `wgpu-info` doesn't have any releases today, so there is nothing to tag. If you want to see it on crates, we can talk about this. Is this really what you need? If I understand correctly, uploading it on crates doesn't make the build reproducible by itself. Only the lockfile does, and it may not necessarily be in the package (since it's outside of the `wgpu-info` folder?). So it could be that crates releases are totally irrelevant to you. The only thing you care about is the lockfile. You are saying, just talking about revisions is inconvenient, and you need a version, right? In this case, once you want to create a new package version for wgpu-info, you could make a PR bumping its `Cargo.toml` version (presumably, in the release branch), and consider the merged revision to match that version. Would that be an appropriate workflow for you?

**Comment by kvark** [comment]
You are asking the right questions!

What is the endgame for the packages here? Since Rust doesn't have an ABI, I imagine you aren't going to include Rust libraries in the package. So the binary targets are the only things you could include. Is that right?

If that's right, then we could name it as `wgpu-utils` package (since it doesn't carry `wgpu` itself). We'd then just tag whatever versions you include in the package. I.e. start with `utils-0.10.0` tag, then once you decide to publish a new version, you pick a revision, and we create `utils-0.10.1` tag, etc. These versions would *not* match the `crates.io` versions of any included crates.

**Comment by kvark** [comment]
The workflow in which we make a tag and then ping you - sounds good to me. In fact, I just created https://github.com/gfx-rs/wgpu/releases/tag/utils-0.10.0 tag to start. If that's useful, we can set up CI jobs to build everything for you. Just need to know what you are doing with the source, and put it into an github action for tags.

**Comment by erictapen** [comment]
That sounds great, thank you very much. No CI job needed for me, we have to build and check the packages ourselves anyway.

**Comment by kvark** [comment]
Thank you for pushing this! On a side note, I'm embracing to try working with NixOS with the next machine I'll hopefully get soon. Will use your example to learn more about the package management :)

**Comment by erictapen** [comment]
Yay, yes come to the NixOS side ;)
