### ISSUE TITLE
Vulkan validation errors when rendering to a texture with `COPY_SRC` enabled

### ISSUE THREAD

**Issue by initial-algebra** [gfx-rs/wgpu#1700]
**Description**
Every time a texture view created from a texture where `usage` includes `COPY_SRC | RENDER_ATTACHMENT` is attached to a render pass, the validation layer throws an error:
```
Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-04627 ] Object 0: handle = 0xd572c4000000000b, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x45125641 | vkCmdBeginRenderPass(): Image view #0 created from an image with usage set as 0x11 but using VkImageViewUsageCreateInfo the inherited usage is the subset 0x10 and the image info #0 used to create the framebuffer had usage set as 0x11
```
This was produced when running `examples/capture`.  The texture is created with only those two usages.  `0x10` = `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT` and `0x11` = `0x10 | VK_IMAGE_USAGE_TRANSFER_SRC_BIT`.  So the `COPY_SRC` usage is somehow lost when beginning the render pass.  The example itself produces the expected output.  In my application, I additionally use `SAMPLED`, which causes the reported bits to be `0x14` and `0x15` respectively (due to `0x4` = `VK_IMAGE_USAGE_SAMPLED_BIT`).

**Repro steps**
Running `examples/capture` is enough on my system.

**Platform**
Windows 10
`wgpu` on latest `master`
RX 590 on Radeon Software Adrenalin 21.5.1
Vulkan SDK 1.2.176.1

**Comment by kvark** [comment]
Since it looked so similar to the older VVL issue, I assumed something is wrong with the VVL install when I saw this. But now I think I see the issue clearly.

We are using `VkImageViewUsageCreateInfo`, and we are passing in the usage that has been filtered (in wgpu-core) from all the bits that aren't applicable (e.g. if it includes multiple mipmap levels, you can't render into it). This stripping also removes the COPY bits, since you can't do any COPY operations on a view (only on textures).

When creating a framebuffer, we need to tell it what usage the images will have. The spec text was quite non-trivial to me, and I read this as - you have to pass the usage of the original texture in. Now, it seems that the VVL are expecting us to pass the usage of the views instead.

I'll work on a fix. Thank you for filing!
