### ISSUE TITLE
Adding a way to query surface support for an adapter

### ISSUE THREAD

**Issue by Lonsdaleiter** [gfx-rs/wgpu#1755]
**Is your feature request related to a problem? Please describe.**
I notice there is no way to query for a given adapter whether it is supported by a surface. The only way to get this information is with request_adapter, which can lead to situations where if one has complex logic for choosing adapters that requires using enumerate_adapters, whether a surface is supported cannot be queried. Also, it makes using multiple surfaces with one adapter difficult to do soundly as you cannot specify that both the surfaces must be supported when picking an adapter.

**Describe the solution you'd like**
A function implemented on the wgpu adapter (say, ```is_surface_supported```) which takes as input a reference to a surface and returns whether that adapter supports this surface (ie. can make a swapchain on and present to it).

**Describe alternatives you've considered**
I'm not really sure what alternative solutions would work here - this feature is pretty straightforward.

**Additional context**
I am a novice contributor, and have yet to contribute properly to wgpu, but would be willing to take a crack at implementing this and making a PR if the change makes sense.

**Comment by kvark** [comment]
I think the key issue here is `enumerate_adapters`, which isn't a part of WebGPU spec.
If the problem was only about `request_adapter`, we'd just make the surface list a parameter instead of a surface option.
I think it's relatively harmless to add the check you are requesting, since on the Web it would just return `true` unconditionally.
