### ISSUE TITLE
Add crate features for backends and shader languages

### ISSUE THREAD

**Issue by codeflo** [gfx-rs/wgpu#1782]
**Is your feature request related to a problem? Please describe.**
wgpu has a large API surface, which is very useful, but also has two important downsides if you don't need everything: executable size and compilation/link time.

A statically linked "Hello, world" program using wgpu is around 6 MB on Windows, which is not completely unreasonable in a practical sense, but not aesthetically pleasing either. The more important point is that linking that executable takes quite a bit of time, which reduces iteration speed during development.

**Describe the solution you'd like**
It would be nice if wgpu allowed disabling some of its larger subsystems via crate features. Two obvious candidates are:

* Backends: For many usecases, it should be enough to include only one backend. For example, it might be very reasonable for a game to only target DX12 on Windows.

* Shader languages: If your program only loads one type of shader, say WGSL, you could remove the other compilers.

Those features could still might be enabled by default, to provide a convenient out-of-the-box experience for new users, but could be disabled via `default-features = false`.

**Describe alternatives you've considered**
An obvious question is whether it's possible to set up the API in such a way that unused features can be removed at link time. For example, if the different shader source types were loaded with different function calls instead of enum variants, the dead code might be eliminated. This would require some larger API changes, however. It also wouldn't help very much with compile times.

**Additional context**
I did a simple experiment to cut out support for non-Vulkan backends and loading non-WGSL shaders. (This was a simple test, I haven't properly measured the impact of those changes in isolation.)

The result was promising. For a static executable in a small program, again on Windows, executable size went down from ~7 MB to ~4 MB. Perhaps more importantly, the link time went down proportionally as well, which was a real quality of life improvement.

**Comment by kvark** [comment]
Thank you for filing this in such a detailed way!

> Backends: For many usecases, it should be enough to include only one backend. For example, it might be very reasonable for a game to only target DX12 on Windows.

Could you provide more details on why you'd want a DX12-only application on Windows, for example?

I think being able to select backends at compile time would be useful, but it's difficult to expose these features in a convenient way. If Cargo allowed the default features to be different per platform, that would help big time.

> Shader languages: If your program only loads one type of shader, say WGSL, you could remove the other compilers.

What you want has already happened in #1518. Today, only WGSL frontend is supported out of the box, and if you want to provide SPIR-V, you'd enable "spirv" feature.

---

There are other ways to fight the linking time in Rust. One is to use an alternate linker (`lld` instead of `ld` - https://brokenco.de/2020/01/08/faster-rust-linking.html). Another is to use dynamic libraries (which are linked independently).

**Comment by codeflo** [comment]
Thanks for the detailed response. I hadn't seen #1518, that's great.

Also, thanks for the tip with lld. I happen to use it already, but I only found out about it about a week ago myself and I think this should be a lot more widely known. Dynamic libraries, unfortunately, have other disadvantages in Rust that need to be balanced against this. But that's out of scope for this discussion I think.

> Could you provide more details on why you'd want a DX12-only application on Windows, for example?

It's a question of development resources mostly. Any configuration option you expose to end users increases optimization and test efforts. I think this is sometimes underappreciated, but a lot of high-impact engineering decisions come from eliminating, rather than introducing, options.

DX12 support now goes so far back even on Intel that you quickly run into a situation where any GPU without DirectX 12 drivers wouldn't run your game anyway, purely for performance reasons.

Several big commercial games are now single-API on Windows, likely those decisions where the result of similar considerations. To pick two well-known examples, Cyberpunk 2077 is DX12 exclusive, and Doom Eternal only runs on Vulkan.

> If Cargo allowed the default features to be different per platform, that would help big time.

Clearly, I now a lot less about Cargo features than I thought I knew: rust-lang/cargo#1197. :( Is there an (even ugly) workaround with intermediate crates, or is this just not possible at all?

**Comment by kvark** [comment]
> It's a question of development resources mostly. Any configuration option you expose to end users increases optimization and test efforts. I think this is sometimes underappreciated, but a lot of high-impact engineering decisions come from eliminating, rather than introducing, options.

Supposing you target DX12 only. Do you want your game to run on Windows 7/8? There is still a whole lot of users there (~20% of windows, according to steam survey), and DX12 native support starts with Windows 10. You have 3 choices from there:
  - drop 20% of users
  - ship with Vulkan (and/or DX11) support enabled in `wgpu`. You'd have to do more testing on these platforms, but hopefully not much target-specific optimizations, because that's our internal task, not yours.
  - use DX12 on DX11 layer provided by Microsoft. This means, you *still* have to do all the testing and optimization for these platforms (code path is entirely different). And in addition, you are coping with one more layer between the application and the HW, which means worse performance.

> any GPU without DirectX 12 drivers wouldn't run your game anyway, purely for performance reasons.

This is correct about the hardware. But software-wise, your platform may be a beast running Windows 7, and it will not have native DX12 support there.
So, with this in mind, keeping it DX12-only doesn't sound like an obvious win to me. Yet, I acknowledge that we still need to provide a way to accomplish it with features (we just don't know how, given the current cargo limitations).

> Several big commercial games are now single-API on Windows, likely those decisions where the result of similar considerations. To pick two well-known examples, Cyberpunk 2077 is DX12 exclusive, and Doom Eternal only runs on Vulkan.

Doom Eternal is an exception rather than the rule. Cyberpunk 2077 runs on Windows 7, so it uses the additional layering that I mentioned. While you can still call it "DX12 exclusive", it's not exclusive in a sense that proves the point of needing only one API. It's rather that the devs didn't have something like `wgpu` available, and they had to take compromises. You see how it turned out - the game runs like sht on Windows 7. Testing and performance both failed.

The rule is quite different - it's UE and Unity, which support multiple backends. I have no idea about the details. Do you know if UE games are able to strip away backends? I'm sure it's theoretically possible with C++ defines and such, I'm curious if people actually do this.

> Is there an (even ugly) workaround with intermediate crates, or is this just not possible at all?

Unfortunately, I don't have an easy workaround. You can basically fork wgpu and disable the backends by hand. It will probably be painless to sync up and rebase on wgpu changes, at least. I'd love to see https://github.com/rust-lang/cargo/issues/1197 resolved, maybe we can put more pressure on them?
