### ISSUE TITLE
[metal] Using workgroup variable causes what is probably a race condition in compute pipelines.

### ISSUE THREAD

**Issue by dragostis** [gfx-rs/wgpu#1823]
Run the `hello-compute` example on macOS on Intel HD630 with:
```diff
--- a/wgpu/examples/hello-compute/shader.wgsl
+++ b/wgpu/examples/hello-compute/shader.wgsl
@@ -5,6 +5,7 @@ struct PrimeIndices {
 
 [[group(0), binding(0)]]
 var<storage, read_write> v_indices: PrimeIndices;
+var<workgroup> foo: u32;
 
 // The Collatz Conjecture states that for any integer n:
 // If n is even, n = n/2
@@ -13,6 +14,7 @@ var<storage, read_write> v_indices: PrimeIndices;
 // Though the conjecture has not been proven, no counterexample has ever been found.
 // This function returns how many times this recurrence needs to be applied to reach 1.
 fn collatz_iterations(n_base: u32) -> u32{
+    foo = 0u;
     var n: u32 = n_base;
     var i: u32 = 0u;
     loop {
```

Most of the times it will run correctly and output `[0, 1, 7, 2]`, but, if you run it in a loop (e.g. `for i in {1..1000}; do cargo run --example hello-compute; done`) it will eventually output `[1, 2, 3, 4]`. This behavior seems to be easier to cause with big inputs.

Also, running it without the `workgroup` variable seems to work fine.

**Comment by kvark** [comment]
> validateComputeFunctionArguments:795: failed assertion `Compute Function(main1): missing threadgroupMemory binding at index 0 for foo[0].'

**Comment by kvark** [comment]
Looks like this is a serious issue. Metal wants use to [setThreadgroupMemoryLength](https://developer.apple.com/documentation/metal/mtlcomputecommandencoder/1443142-setthreadgroupmemorylength?language=objc) on each threadgroup input, which also needs to be annotated accordingly as `[[threadgroup(N)]]`

This is very silly, since the shader already knows exactly how much memory it takes, and yet we'll need to write code to grab that data and set its size on the API side. Maybe it's not too bad, given that we need to validate the amount of consumed workgroup memory anyway...

This are the concrete steps, all within wgpu-hal for now:
  - shader module creation should collect the list of workgroup variable sizes for each compute entry point
  - when a compute pipeline is created, it gets the relevant EP list associated
  - compute pass state knows about each threadgroup ID -> size
  - binding a compute pipeline changes some of these, which need to be reset on the `MTLComputeCommandEncoder`.
