### ISSUE TITLE
"comparison flag doesn't match the shader" in wgpu 0.10

### ISSUE THREAD

**Issue by ecton** [gfx-rs/wgpu#1841]
**Description**
I have a pre-existing SPIR-V fragment shader that is causing errors on wgpu 0.10 that previously caused no errors. The error I'm getting is:

```
[2021-08-21T18:36:26Z ERROR wgpu::backend::direct] wgpu error: Validation Error
    
    Caused by:
        In Device::create_render_pipeline
        error matching FRAGMENT shader requirements against the pipeline
        shader global ResourceBinding { group: 1, binding: 1 } is not available in the layout pipeline layout
        comparison flag doesn't match the shader
```

The glsl source, compiled using `glslc`, for the fragment is pretty simple:

```
#version 450

layout(set = 1, binding = 0) uniform texture2D tex;
layout(set = 1, binding = 1) uniform sampler   sam;

layout(location = 0) in  vec2  f_uv;
layout(location = 1) in  vec4  f_color;

layout(location = 0) out vec4 fragColor;

void main() {
	vec4 texel = texture(sampler2D(tex, sam), f_uv);

	fragColor = vec4(
		mix(texel.rgb, f_color.rgb, f_color.a),
		texel.a
	);
}
```

The `BindingType::Sampler` being specified contains comparison set to true. If I change it to false, I get this error (now at a later point in the initialization process):

```
[2021-08-21T18:42:36Z ERROR wgpu::backend::direct] wgpu error: Validation Error
    
    Caused by:
        In Device::create_bind_group
        sampler binding 1 expects comparison = false, but given a sampler with comparison = true
```

This leads me to suspect that the cause of this error is that my SPIR-V shader doesn't contain the right information that naga needs to determine that I'm wanting the comparison function enabled.

I'm uncertain if it's because I have bad glsl or if it's a bug.

**Repro steps**

Sadly, it's not super-small but [this branch of Kludgine](https://github.com/khonsulabs/kludgine/tree/wgpu-0.10) can be used to reproduce this issue. Any example causes it, as the pipeline is always enabled. E.g., `cargo run --example simple`

**Expected vs observed behavior**

The app panics instead of executing.

**Platform**
I don't think it's relevant, but Manjaro Linux using x11 with proprietary nvidia drivers.

**Comment by cwfitzgerald** [comment]
So this is because you attach a sampler which has the depth comparison set to Some. You can only use a depth comparison sampler when doing depth compares.

**Comment by ecton** [comment]
Pardon my ignorance, but I am trying to do depth-enabled comparisons. There is a depth buffer.

**Comment by cwfitzgerald** [comment]
Yeah, so the depth buffer you've attached is used to determine if the value from the fragment shader should be written at all. This happens (in theory) once the fragment shader finishes, implicitly because you have it configured as part of the pipeline state.

Comparison samplers are useful when you need to read a value from _a_ depth buffer in your shader. This is done with sampler2DShadow. You can set this in action in the shadow example where we use it to determine if a given pixel is in light or in shadow.

In this case you're reading from a regular texture and outputting that into the screen, because you don't rant to do a depth comparison _when reading the texture_ you should use a non-comparison sampler.

**Comment by ecton** [comment]
@cwfitzgerald Thank you so much. That explanation helped me piece together my folly.

**Comment by cwfitzgerald** [comment]
Great!
