### ISSUE TITLE
Rendering performance drop when updating wgpu from v0.6 to v0.9 on macOS

### ISSUE THREAD

**Issue by HolgerGottChristensen** [gfx-rs/wgpu#1842]
**Description**
When updating from wgpu 0.6 to 0.9 the performance of the rendering on macOS dropped dramatically. I have tried to narrow down the performance, and have noticed that when I remove the for loop in my blur shader that the performance goes back to normal. I have tried downgrading to 0.8 but the the performance is still the same as 0.9.  

My shader is GLSL compiled to spirv using shaderrc 0.7.2. When running with wgpu 0.8 it gives me:
```
[2021-08-22T12:25:29Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
```
once, and when running it with 0.9 it gives the same error twice. It did not give me those errors when using wgpu 0.6 which I guess is because the shader validation has become more sophisticated (I don't know what this error means, and how to fix it). I have included the shader code in the extra materials section.

**Repro steps**
Clone [https://github.com/HolgerGottChristensen/carbide](https://github.com/HolgerGottChristensen/carbide) and run the blur_filter example from backends/carbide_wgpu/examples. The specific shader can be found under backends/carbide_wgpu/src as filter.frag. In the commit 57d1c5016e0ba5dfff5f01ca40d705071e6c78b2 the code uses v0.6 and performs well. I understand this is not a minimum example and if needed I will try to provide one.

**Expected vs observed behavior**
When running the code (with the motion blur enabled in the shader) with wgpu v0.6 the frame rate is pretty good, but when updating to v0.8-0.9 it slows down significantly on macOS. When running with the 7x7 gaussian blur it freezes my computer fully and I am only able to stop it by holding down the power button.

**Extra materials**
In the zip, I have provided the fragment shader and the compiled spirv.
[filter_shaders.zip](https://github.com/gfx-rs/wgpu/files/7027341/filter_shaders.zip)

**Platform**
I am running macOS 10.15, using wgpu 0.9.

I hope the information provided is enough to start with, otherwise I will try to provide more.

**Comment by HolgerGottChristensen** [comment]
For those interested, I have included the shader compiled to metal using Naga: 
[filter.metal.zip](https://github.com/gfx-rs/wgpu/files/7027664/filter.metal.zip)

**Comment by HolgerGottChristensen** [comment]
Below is the same shader compiled with spirv-cross that was included in spirv_cross-0.23.1 rust binding.
```metal
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

constant spvUnsafeArray<float4, 7> _48 = spvUnsafeArray<float4, 7>({ float4(-3.0, -3.0, 0.0, 0.14285714924335479736328125), float4(-2.0, -2.0, 0.0, 0.14285714924335479736328125), float4(-1.0, -1.0, 0.0, 0.14285714924335479736328125), float4(0.0, 0.0, 0.0, 0.14285714924335479736328125), float4(1.0, 1.0, 0.0, 0.14285714924335479736328125), float4(2.0, 2.0, 0.0, 0.14285714924335479736328125), float4(3.0, 3.0, 0.0, 0.14285714924335479736328125) });

struct main0_out
{
    float4 f_color [[color(0)]];
};

struct main0_in
{
    float2 v_tex_coords [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> t_diffuse [[texture(0)]], sampler s_diffuse [[sampler(0)]])
{
    main0_out out = {};
    float2 texelSize = float2(0.001562500023283064365386962890625, 0.00234741787426173686981201171875);
    float4 color = float4(0.0);
    for (int i = 0; i < 7; i++)
    {
        color += (t_diffuse.sample(s_diffuse, (in.v_tex_coords + (texelSize * _48[i].xy)), level(0.0)) * _48[i].w);
    }
    out.f_color = color;
    return out;
}
```

**Comment by HolgerGottChristensen** [comment]
Here you have a trace. It is created without the cross feature enabled.

[trace_for_blur_filter.zip](https://github.com/gfx-rs/wgpu/files/7028295/trace_for_blur_filter.zip)

**Comment by kvark** [comment]
Thank you for filing! It's a pleasure to work on an issue with so much details provided 👍 

Contrary to @m4b warnings, this isn't a Metal backend issue. It may be argued that this isn't even a bug, strictly speaking.
Your GLSL code looks fine. However, `wgpu` doesn't work with GLSL (it works with WGSL, where you'd not have this problem). You are producing SPIR-V first, and that's what [we see there](http://shader-playground.timjones.io/af6ed31b8a79b89e9727625db69e028f):
```
%48 = OpConstantComposite %_arr_v4float_uint_7 %36 %38 %40 %41 %43 %45 %47
...
  OpStore %indexable_0 %48
  %72 = OpAccessChain %_ptr_Function_v4float %indexable_0 %70
```
So "%48" is your constant array. Every time it's indexed (! every iteration), SPIR-V issues an `OpStore` of the value of the array into a local variable. The MSL generated code (by Naga) does precisely that, so it faithfully translates the SPIR-V that you are feeding. Naga doesn't do any optimization passes, and it's not in the near plans.

The reason why SPIR-V is generated to `OpStore` into a variable is because SPIR-V doesn't support dynamic indexing into constants. This restriction is also inherited in WGSL, hence I said you wouldn't have this problem there. As to why `OpStore` is done on every iteration - that's just `shaderc` being silly. It should have instead put a single `OpStore` at the beginning of the program and be done with it.

From the high level, this is one of the issues that you are hitting because you aren't using WebGPU in a way it's meant to be used (with WGSL). Instead, you are enabling the "spirv" feature and feeding something that you don't control directly (the output of `shaderc`).

Not entirely sure how actionable this issue is. Would we need some kind of heuristics in the SPIR-V frontend to detect this pattern as something specific produced by `shaderc`? That would be quite sad.

In the meantime, you can work around it by not using a constant array, or by putting it into a variable.
