### ISSUE TITLE
References to removed APIs in Firefox Nightly with web-sys 0.3.51

### ISSUE THREAD

**Issue by hwoodiwiss** [gfx-rs/wgpu#1843]
**Description**
Error thrown when attempting to get prefered Swapchain Format - 
Uncaught (in promise) TypeError: getObject(...).getSwapChainPreferredFormat is not a function

Some investigation indicates that this is due to the version of web-sys (=0.3.51) used in WGPU v0.9 and v0.10.0 not matching the current state of FF nightly API-wise.

**Repro steps**
Usage of any of the js APIs that have recently been removed from FF nightly and web-sys (SwapChain related things mostly).
Can be seen here: https://orange-sand-08e3a2703.azurestaticapps.net/ which is populated from this repo/branch https://github.com/hwoodiwiss/learn-wgpu/tree/wasm-broken-example

**Expected vs observed behavior**
I get a non-working application, I had no expectation, I'm aware that I'm in un-stable API teritory.

**Platform**
Windows 10 Pro x64, wgpu v0.9 or v0.10.1 (Tried with both) on Firefox Nightly, notably stopped working between 16 - 20 of August (Not 100% which day sadly).

**Comment by ifsheldon** [comment]
Also waiting for this to be fixed. It seems more tests need to be added when a new release is published.

**Comment by grovesNL** [comment]
@ifsheldon the WebGPU web API is currently unstable, so we can't guarantee that WebGPU implementations (e.g. Firefox Nightly, Chrome Canary), web-sys bindings, and wgpu web backend all align during releases (generally at least one will quickly become stale even if they happen to line up). We try to keep them as close as possible but they still fall out of sync every once in a while. If you need guarantees about this working, at the moment it would be best to pin the version of wgpu and the browser you're using temporarily at known good points

**Comment by ifsheldon** [comment]
Yeah, I know, so I don't expect `wgpu` new releases won't break anything and by "more tests" I meant basic tests on examples, since the [wgpu wasm guide](https://gfx-rs.github.io/2020/04/21/wgpu-web.html) out there refers to the code examples in wgpu, so I think at the very least, these examples should compile and run fine. I know they are runnable on non-wasm targets, but why not ensures them runnable on wasm as well?

**Comment by cwfitzgerald** [comment]
As of right now, with WebGPU being unstable, we don't gate releases on being able to run on the browser, if we did we would end up delaying releases by months in some cases.

In addition there will always be time where wasm code is broken on new browsers. The browser updates, then we have to update the web_idl, then we have to update web_sys, then we have to adjust our use of the bindings. This process takes time (and is currently running right now) and the whole time `wgpu` on WebGPU will be broken.

We understand this isn't ideal, but until WebGPU is stabilized, is just the dance we have to play.

**Comment by ifsheldon** [comment]
I see, but can we as least ensure examples can run on one specific version/release of one browser and explicitly pin the version/release in tutorials? I mean, that's what we expect examples and tutorials to do, right? This should not take as much effort as making sure all examples runnable on all releases of all browsers. Imagine if you were a new comer to WebGPU, although you know the APIs are changing rapidly, it will be frustrating if you don't even know how to make examples work (in this case, meaning work on wasm).

**Comment by grovesNL** [comment]
@ifsheldon I understand your concern and we definitely want to improve the experience for newcomers. Fortunately there should be fewer breaking changes in the future, so hopefully most situations like this will be avoided.

Generally we do try to keep everything in sync so that the examples run in at least one browser, but sometimes the timing doesn't work out (usually the browser API is a few breaking changes behind or ahead of wgpu-rs). Instead of pinning release versions, usually the `master` branch is the best branch to use with wasm + the latest Firefox Nightly or Chrome Canary
