### ISSUE TITLE
SPIR-V use locked out by wgpu 0.10

### ISSUE THREAD

**Issue by StephanvanSchaik** [gfx-rs/wgpu#1851]
**Is your feature request related to a problem? Please describe.**
I am currently using wgpu as a cross-platform abstraction for native to avoid having to implement my own renderer on top of Vulkan, Direct3D, Metal, OpenGL, etc. and I am not a web user. My shaders are currently written in GLSL, and I do not intent to port them to WGSL (not really a fan of WGSL, but looking forward to rust-gpu). In fact, naga does not even fully support all of my shaders and will therefore not be able to convert them to WGSL (I already opened issues for naga, but among the issues I have found I need advanced compute features like atomics). In the past, it was possible to just use shaderc to compile my shaders to SPIR-V and pass them directly to wgpu (again using shaderc because naga is no way mature enough to handle my use cases), with the exception that the validation would fail because naga does not support the features I need.

I also don't like that WebGPU seems to follow the same route as OpenGL where GLSL used to be the only source language, but that is completely subjective. I just don't see the reason to compile GLSL to SPIR-V to WGSL to the language actually required by the backend.

**Describe the solution you'd like**
Currently wgpu 0.10 seems to support a way of passing SPIR-V that is gated behind the "spirv" feature flag. One issue with this is that the documentation mentions that this is only supported by Vulkan. I would like this to be supported by all the backends so I can continue using SPIR-V, and therefore GLSL, with wgpu. Even if it is just feature gated.

**Describe alternatives you've considered**
As described before, WGSL does not work for my use case, which means I can upgrade to 0.10 with no guarantee of SPIR-V support outside of Vulkan (correct me if I am wrong) or being stuck on 0.9 for now where all of this just used to work.

**Additional context**
N/A

**Comment by genusistimelord** [comment]
I agree with this as well as I am having the same thought on the issue. As WGSL does not yet support enough features to even be main stream and GLSL currently is still used more than WGSL for many things. I do not think its a good idea to get rid of full SPIR-V support at least if you don't want to implement a GLSL back-end that Actually works for everything. Naga also should be a option and not a pure end to the issue as well as naga wont be mature enough for a while to support every case that GLSL could possibly do including Older shader methods that Naga might not even be looking at since WGSL does not and will never support them. 

Overall we simply ask that you re-add SPIR-V support back in full for all the native systems as a Secondary choice behind a feature gate.

**Comment by cwfitzgerald** [comment]
Thank you both for filing.

I want to clarify here that there are actually two different features for using spirv.

1. Passthrough: This is gated on `Feature::SPIRV_PASSTHROUGH` and uses `create_shader_module_spirv`, which is unsafe, and the feature is only exposed on vulkan. In this case we don't parse your shader and just plop it on the gpu.
2. Parsed: this is gated by the `spirv` feature. It enables the `spv-in` feature of naga which allows naga to parse (and generate non-spirv) shaders given to us in spirv.

Neither of these features are going to be going away. While WebGPU may only support WGSL we do not necessarily have to.

The first one only exists on vulkan because that is the only platform that injests spirv natively. We use naga to translate your shaders, and if naga can't parse the shaders we can't use it to translate your shader to the source language. 0.9 and before used an external C dependency, spirv-cross to do this translation. When we rewrote our hal, we dumped support for spirv-cross and the _many_ problems it has caused us.

The second one is gated behind a feature because enabling spv-in requires enabling quite a few dependencies in naga to be able to parse spirv down, so we keep it optional.

In addition, even if we were to only support WGSL, or you were to want to run on WebGPU (which does only support WGSL), you can use naga's `spv-in` and `wgsl-out` to translate from spirv to wgsl either at runtime or at build time. In the future, you will be able to use naga to read your GLSL directly and output spirv either or wgsl.

Finally, we encorage you to file issues if naga chokes on your shaders in ways that aren't already known issues. Naga has had a _ton_ of work on it lately, so it may support more than you realize.

If it inspires any confidence, my main project, rend3 uses GLSL as its source language, compiling to spirv, due to the project using descriptor indexing which naga can't currently parse. All descriptor-indexing shaders are properly parsed by naga's spirv frontend, allowing me to run that path on all 4 exposed backends.

**Comment by StephanvanSchaik** [comment]
Hi,

Thanks for your quick reply. I wasn't sure if the second option was still around, because it wasn't entirely clear to me from the documentation. Thank you for clearing that up, and I hope this difference can also be a bit clearer in the documentation. This is at least helpful because it means we can still rely on having a SPIR-V path to use in wgpu for most of the shaders. I will have to investigate that route again, because I think I ran into an issue where the spv-in side of naga does not support passing arrays as vertex attributes from the vertex shader to the fragment shader yet, but at least I do have a workaround for that in the meanwhile (I also opened an issue for this one).

Don't get me wrong, I agree that naga is the way forward, and I am hoping that I will also be able to use naga in the near future instead of shaderc, as that is currently the only non-Rust dependency left for me. It is just that naga is also a bit inconvenient because of the early adoption where it is still missing some of the features for compute shaders like atomics and barriers (from what I understand these may not yet be supported by spv-in either, which might be going to block some of my work until that support actually lands). Again, I opened issues where I can and will do so in the future if I find more issues.

At least I am glad that using SPIR-V is still a viable option, because that was a major concern for me with wgpu 0.10.

**Comment by kvark** [comment]
Thanks @cwfitzgerald for great description of the current state of things, and I'd like to extend it even more.

I know people use SPIR-V, often compiling from GLSL, and users still want this path to work. Problem is: developing a full-features SPIR-V frontend is great amount of work! SPIR-V input in Naga is one of the most complex parts of the project, and it doesn't work very well. It's just a very complicated piece of technology, hence we hide it behind a "spirv" feature now.

One big problem is control flow. @JCapucho is about to try rewriting it completely, because SPIR-V is a mess. The specification is incomplete, and we have to gather pieces of information from other sources, like SPIRV-Tools, or Tint code. The control flow resolver today makes mistakes (producing wrong IR!) and fails on some things.

Another big problem is conceptual that SPIR-V is designed to be closer to hardware and less good as an intermediate compiling step. See http://kvark.github.io/spirv/2021/05/01/spirv-horrors.html. This manifests in the atomics story in particular, which you mentioned. Atomics and barriers *are* supported in Naga. We have tests and user projects taking advantage of them, like https://github.com/kvark/vange-rs . They are supported *except* in SPIR-V and GLSL frontends, where parsing them is really complicated, and we haven't found time/energy to put in a proper solution yet.

I know this is what you aren't intending to do, but that's basically my recommendation: try WGSL. It's designed specifically so that the shader translation is painless, and the language itself is more clear and modern than GLSL. It supports multiple entry points, good entry point interface, type inference, and other essential things. Most importantly, it's the fastest way on run-time and build-time.

Sorry for the lack of issue references. If you are curious about helping on any of the SPIRV frontend issues (like atomics), I'd be more than happy to mentor and explain the situation. Jumping on "#naga:matrix.org" would be most efficient for this discussion.
