### ISSUE TITLE
Support normalized 16-bit texture formats

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1934]
**Is your feature request related to a problem? Please describe.**
It's often convenient to process the data in shaders as `u16` and store it this way. However, reading it in the shader is problematic: currently we have no 16-bit normalized formats, so it has to be bound as integer. But integer textures can't be sampled. So using them is highly restricted today without the normalization.

**Describe the solution you'd like**
Exposed a set of 16-bit normalized formats gated by a feature.

**Describe alternatives you've considered**

**Additional context**
Requested on matrix.

**Comment by aloucks** [comment]
I was looking into the details of this to see if I could implement it when I get some free time and noticed that the existing texture format features all have a `TEXTURE_COMPRESSION_` prefix, rather than `TEXTURE_FORMAT_`, and the 16bit formats are not related to compression.

Would you be open to adjusting the naming of the existing texture format features? It would be nice if they all followed the same pattern, such as `TEXTURE_FORMAT_{family}`.

Currently the compressed formats have features like `TEXTURE_COMPRESSION_ETC2` and `TEXTURE_COMPRESSION_ASTC_LDR`.

I'm suggesting changing these to allow for other (non-compression formats) to all follow the same convention.

e.g.

```rust
// Enables ASTC family of compressed textures ...
TEXTURE_FORMAT_ETC2

// Enables ASTC family of compressed textures ...
TEXTURE_FORMAT_ASTC_LDR

// Enable additional 16-bit texture formats ...
TEXTURE_FORMAT_16BIT
```

**Comment by kvark** [comment]
We should name the features the same way as WebGPU spec does it, unless there is a really strong reason to diverge.

**Comment by VincentJousse** [comment]
@kvark Will this become a WebGPU feature any time soon ?

**Comment by kvark** [comment]
I'm not participating in this standard body any more.
Redirecting to @jimblandy
