### ISSUE TITLE
Improve actionability of "resolver = 2" error

### ISSUE THREAD

**Issue by alice-i-cecile** [gfx-rs/wgpu#2217]
Bevy users have been getting an error that looks like:

> error: DX12 API enabled on non-Windows OS. If your project is not using resolver="2" in Cargo.toml, it should.

This is not very actionable or accessible for new users. Ideally, this error could be made somewhat more verbose to explain how to do this (and mention that they could swap to Rust 2021 instead).

Motivated by https://github.com/bevyengine/bevy/issues/3205

**Comment by thechubbypanda** [comment]
The docs that explain this: https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions

**Comment by Imberflur** [comment]
In regards to Rust 2021, I would like to note that it is somewhat misleading with respect to workspaces since you will need to specify `resolver="2"` in the workspace `Cargo.toml` regardless of the Rust edition being used for the contained crates.

**Comment by fintelia** [comment]
If you don't want to include a more complete description in the error message, including a link could still provide a hint of where to find more details. Either to the page @thechubbypanda suggested, to this issue, or whatever

**Comment by alice-i-cecile** [comment]
Some users aren't seeing this error at all: I'm not entirely sure why, and can't reproduce locally on Windows 10 :(

**Comment by Imberflur** [comment]
Cargo added a warning when the resolver isn't explicitly specified in a workspace containing crates using newer editions: https://github.com/rust-lang/cargo/pull/10910

Although, this probably doesn't completely address the issue since a user could still explicitly set `resolver = 1`. Also, if `wgpu` is already a dependency, I suspect the new warning would still get lost in the errors that are generated when the resolver is not 2.

**Comment by cwfitzgerald** [comment]
This isn't going to be a problem anymore as we shouldn't require it as of v0.16.0
