### ISSUE TITLE
Colors are not rendered as expected

### ISSUE THREAD

**Issue by norman784** [gfx-rs/wgpu#2326]
Why colors are not accurate? Changing the clear color from `hello-triangle` to [rgb(85, 160, 158)](https://duckduckgo.com/?q=%2355a09e&t=osx&ia=answer) is giving me this result.

Side by side comparison:

![image](https://user-images.githubusercontent.com/204656/147595456-2382857a-8694-4659-b16b-da95494e5959.png)

> Left is from the triangle window and right is the color rendered by the web browser.

So my question is, what I need to do in order to make the colors to match?

**Comment by kvark** [comment]
Generally you see colors different because of sRGB framebuffer color. So if you need a particular color in the output, and you are using sRGB surface format, you'd want to transform your color like here - https://github.com/three-rs/three/blob/07e47da5e0673aa9a16526719e16debd59040eec/src/color.rs#L39

**Comment by norman784** [comment]
Thanks it did the trick.

Any recommended documentation/article about the subject so I can learn more about this?

**Comment by kvark** [comment]
I don't have a special recommendation, but visiting the links in the linked source could be a start:
- https://en.wikipedia.org/wiki/SRGB
- https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_sRGB_decode.txt
