### ISSUE TITLE
Support video encoding and decoding APIs

### ISSUE THREAD

**Issue by zmerp** [gfx-rs/wgpu#2330]
[Vulkan Video extensions](https://www.khronos.org/blog/an-introduction-to-vulkan-video) were announced earlier this year and GPU vendors are working on the support. At the time of writing, [this](https://www.phoronix.com/scan.php?page=news_item&px=Vulkan-Video-Mesa-Progress)/[this](https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-470.62.12-Beta-Linux) is the state of the art.

More recently it was announced the [Direct3D 12 Video API](https://docs.microsoft.com/en-us/windows/win32/medfound/direct3d-12-video-overview). Encoder support landed this month.

It would be valuable for wgpu to provide a backend agnostic API for video encoding/decoding, even within a separate crate.

**Comment by sh7dm** [comment]
Vulkan video is still in the development. Support pending for AMD/Intel, so first these can be used:
Linux - VA-API (can be made to work over VDPAU on NVIDIA)
macOS - AVFoundation (does MoltenVK already support Vulkan video extensions?)
Windows - DX12 Video API (probably DXVA on DX11?)

Probably waiting for at least a couple months will be better, since RADV/ANV/MoltenVK/Windows drivers need to mainline and stabilize extensions, then something could be made as an example on top of `ash` and then integrated into wgpu.
It would be a bit hard to implement video on backends other than Vulkan, since it would be necessary to import frames as DMA-BUFs (or similar objects named differently on a platform) from another library to maintain zero-copy GPU memory ops (similar to #1733).

**Comment by cwfitzgerald** [comment]
I don't think this is really in-scope for wgpu itself to handle in its current form. We do, however want to have the interop capabilities so users could implement this themselves and use the decoded result in wgpu.

Additionally these apis are _very_ low level, so the right api would probably need a lot of experimentation, that should be done out-of-repo.

**Comment by jondo2010** [comment]
Relevant project: https://github.com/software-mansion/smelter
