### ISSUE TITLE
Why is the GL backend not available on Windows?

### ISSUE THREAD

**Issue by UE2020** [gfx-rs/wgpu#2369]
**Is your feature request related to a problem? Please describe.**
I'm confused as to why the GL backend is not available on Windows, especially considering that GL is a cross-platform API. Having GL support for Windows would be beneficial in cases where the host machine doesn't have DX12 and Vulkan (iirc, the DX11 backend is not completed).

**Describe the solution you'd like**
Add support for the GL backend on Windows.

**Describe alternatives you've considered**
Not add support for the GL backend on Windows, though I don't see why adding the GL backend to Windows would be too hard.

**Comment by kvark** [comment]
One of the most painful parts of GL support is the context provider and window system integration. We've spent significant effort to work with EGL, and that's the leading context provider for GL on Unix, where GL is formely the leading API. It's a great time sink.
On Windows, we'd need to have WGL support, and I imagine a whole lot of driver bugs, since very very few games actually shipped GL on Windows.

If you want to contribute WGL support, we'll review it and potentially merge.
My preference would be to get DX11 instead, it's long overdue.

**Comment by cwfitzgerald** [comment]
We now have GL support over ANGLE which provides EGL on windows. It's no replacement for DX11, but it's there, so I'm going to close this Any help on the DX11 backend is always appreciated.
