### ISSUE TITLE
English name and proper nouns

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu#2398]
This is awkward: WGPU is an acronym, but also a proper noun, only you can't spell it out since WGPU != WebGPU.

`wgpu` is the crate name, no problem. But, sooner or later, it's nice to have a simple English name and not force people to write `wgpu` everywhere. So, what?

- WGPU? It's an acronym anyway, so why not?
- Wgpu? This feels a little wrong, but still acceptable.
- wgpu? Normally, proper nouns are capitalised for a reason: to make them Stand Out in the middle of a sentence. wgpu doesn't.
- wGPU? (Added for completeness.)

**Comment by kvark** [comment]
This is a really tough problem!
Personally, I tried to keep it lowecase `wgpu`, but then in some contexts it really needs to Stand Out.
There is a bit of a problem with "Wgpu" because it stresses more on the Web and less on GPU, while the project itself is more of an opposite :)
Could also consider "wGPU" for completeness :)

**Comment by dhardy** [comment]
For what it's worth, I've just switched to using WGPU after someone pointed out I really shouldn't confuse `wgpu` and WebGPU.

**Comment by cwfitzgerald** [comment]
I think we can default to `wgpu` (with formatting as code) or "wgpu" as the preferred spelling. That's what we use in our documentation.
