### ISSUE TITLE
Vertex pulling on Metal

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2432]
In order to make vertex attribute data safe, we need to generate MSL that does vertex pulling manually based on the vertex index. Most of the work here would fall on Naga, but wgpu needs to provide the necessary plumbing.

**Comment by bradwerth** [comment]
Had a conversation with @jimblandy where we came up with a different summary of this issue. We need to make drawIndexed* functions generate the same code that the corresponding draw* functions would generate, with the additional guarantee that every vertex referenced by an index is within bounds of the vertex buffer.

Indices out of bounds should invalidate the entire draw call for `GPUPrimitiveTopology` of 'line-strip' and 'triangle-strip'. The other topologies 'point-list', 'line-list', and 'triangle-list' make it possible to spot-remove elements with invalid vertices, but that is fairly arbitrary. For now at least, an OOB index will cause the entire draw call to no-op.

**Comment by jimblandy** [comment]
It seems like the "Note:" at the end of the [definition of `drawIndexed`](https://gpuweb.github.io/gpuweb/#dom-gpurendercommandsmixin-drawindexed) gives us some alternatives:

> Note: a valid program should also never use vertex indices with [GPUVertexStepMode."vertex"](https://gpuweb.github.io/gpuweb/#dom-gpuvertexstepmode-vertex) that are out of bounds. WebGPU implementations have different ways of handling this, and therefore a range of behaviors is allowed. Either the whole draw call is discarded, or the access to those attributes out of bounds is described by WGSL’s [invalid memory reference](https://gpuweb.github.io/gpuweb/wgsl/#invalid-memory-reference).

That last clause there about treating it like an "invalid memory reference" means that we have the same options as for dealing with out-of-bounds array indices in WGSL. This includes returning zeros, or returning data from elsewhere in the array.

I think tossing the entire draw call would be a little hard to implement. There isn't any way that I'm aware of for a vertex shader to cancel the draw call. Producing a [zero value](https://gpuweb.github.io/gpuweb/wgsl/#zero-value-builtin-function) might be the easiest for users to debug.

**Comment by bradwerth** [comment]
Also seems like this doesn't involve Naga at all. If the goal is to turn a drawIndexed call into a draw call, that involves:
1) Create a temp vertex buffer big enough to contain `index_count` vertex data.
2) Fill that new buffer with data from the existing mapped vertex buffer using `first_vertex` and `index_count`, clamping to the vertex buffer's count, filling with zeroes for OOB.
3) Map the new buffer as the vertex buffer.
4) Submit the draw call with `[0, index_count]` vertices.
5) Map the original vertex buffer.
6) Destroy the temp vertex buffer.

No Naga, right?

**Comment by bradwerth** [comment]
> Also seems like this doesn't involve Naga at all.

I suppose unless we try to solve this with a compute shader to do all the indexing and bounds-checking, which is definitely a Naga solution.

**Comment by bradwerth** [comment]
One more alternative, it could be done my modifying the index buffer in-place (if it is modifiable during the scope of `draw_indexed`). That would be destructive, though, and also would require us to choose an arbitrary "safe" index.

**Comment by grovesNL** [comment]
Is there a reason we'd prefer to avoid vertex pulling here? Vertex pulling should be able to inject bounds checks directly into vertex shaders wherever the attributes are first loaded, so I think we'd be able to avoid buffer copies/separate compute shader for validation.

**Comment by cwfitzgerald** [comment]
Additionally, Apple and AMD gpus already do vertex pulling, so there shouldn't be any significant performance penalties to this.

**Comment by bradwerth** [comment]
> Is there a reason we'd prefer to avoid vertex pulling here?

Not at all, I just don't understand vertex pulling adequately. My idea of "make drawIndexed into draw" is just my fumbling attempt to define this idea. If there are gpu features that we can access to do this, leaving the drawIndexed calls alone, please direct me to some documentation of the feature(s) we need to be using.

**Comment by cwfitzgerald** [comment]
@bradwerth Ah alright!

Vertex pulling is basically instead of using traditional vertex attributes to get the input vertex data, you bind your vertex buffers as storage buffers and use the `@builtin(vertex_index)` to index into them. AMD and Apple already do this under the hood (as they have no dedicated vertex hardware). In this case, by us explicitly "pulling" from storage buffers, this gives us a chance to insert bounds checks.

Notably it's very important to keep the index buffer around, as gpus use the index buffer to deduplicate vertex shader invocations.

**Comment by jimblandy** [comment]
> Is there a reason we'd prefer to avoid vertex pulling here? Vertex pulling should be able to inject bounds checks directly into vertex shaders wherever the attributes are first loaded, so I think we'd be able to avoid buffer copies/separate compute shader for validation.

Yeah, this is what I would expect to be going on. You'd set an option in `naga::back::msl::Options` that would say, "please generate code for vertex shader entry points that accepts a vertex id and does the indexing into the buffer itself (i.e. 'vertex pulling', after clamping the index."

For example, in the [Metal Shading Language Specification Version 3.1](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf), page 95 shows MSL code for a vertex shader:

```
struct VertexOutput {
  float4 position [[position]];
  float4 color;
  float2 texcoord;
};
struct VertexInput {
  float4 position;
  float3 normal;
  float2 texcoord;
};
constexpr constant uint MAX_LIGHTS = 4;
struct LightDesc {
  uint num_lights;
  float4 light_position[MAX_LIGHTS];
  float4 light_color[MAX_LIGHTS];
  float4 light_attenuation_factors[MAX_LIGHTS];
};
vertex void
render_vertex(const device VertexInput* v_in [[buffer(0)]],
              constant float4x4& mvp_matrix [[buffer(1)]],
              constant LightDesc& light_desc [[buffer(2)]],
              device VertexOutput* xform_output [[buffer(3)]],
              uint v_id [[vertex_id]])
{
  VertexOutput v_out;
  v_out.position = v_in[v_id].position * mvp_matrix;
  v_out.color = do_lighting(v_in[v_id].position,
                            v_in[v_id].normal, light_desc);
  v_out.texcoord = v_in[v_id].texcoord;
  // Output the position to a buffer.
  xform_output[v_id] = v_out;
}
```

This shows the `render_vertex` function accepting a pointer `v_in`, whose `[[buffer(0)]]` attribute means that it points to the entire buffer of vertex inputs. The function also accepts `v_id`, which the `[[vertex_id]]` attribute marks as the index to use into the the buffer `v_in`. These explicit indexing operations into the entire buffer are what's meant by "vertex pulling".

In an indexed draw call, `v_in` is the value drawn from the index buffer, and since that buffer's contents are supplied by web content, they could be out of range. This is the condition Firefox's WebGPU implementation needs to guard against.

Here's how that same shader would be written in WGSL:

```
struct VertexOutput {
  @builtin(position) position: vec4<f32>,
  @location(0) color: vec4<f32>,
  @location(1) texcoord: vec2<f32>,
}

struct VertexInput {
  @location(0) position: vec4<f32>,
  @location(1) normal: vec3<f32>,
  @location(2) texcoord: vec2<f32>,
}

const MAX_LIGHTS: u32 = 4;

struct LightDesc {
 num_lights: u32,
 light_position: array<f32, MAX_LIGHTS>,
 light_color: array<f32, MAX_LIGHTS>,
 light_attenuation_factors: array<f32, MAX_LIGHTS>,
};

@group(0) @binding(0) var<uniform> mvp_matrix: mat4x4<f32>;
@group(0) @binding(1) var<storage> light_desc: LightDesc;

@vertex
fn render_vertex(v_in: VertexInput) -> VertexOutput
{
  var v_out: VertexOutput;
  v_out.position = v_in.position * mvp_matrix;
  v_out.color = do_lighting(v_in.position,
                            v_in.normal, light_desc);
  v_out.texcoord = v_in.texcoord;
  // Output the position to a buffer.
  return v_out;
}

fn do_lighting(position: vec4<f32>, normal: vec3<f32>, light_desc: LightDesc) -> vec4<f32> {
  // blah blah blah
  return vec4<f32>(0);
}
```

There are three main differences from the Metal version:

- The `mvp_matrix` and `light_desc` arguments in the MSL code become global variables in the WGSL code. This is a general WGSL/Metal difference: buffers, textures, and shaders are global variables in WGSL, but arguments to the entry point in Metal.

- The Metal code writes its result to `*xform_output`, whereas WGSL returns it as the function's return value. This is mostly cosmetic.

- The interesting change: Metal's `render_vertex` gets passed `v_in` as an *array*, which it indexes by the `[[vertex_id]]` argument `v_id`, whereas WGSL's `render_vertex` gets passed a single *element* of the array as `v_in`. In other words, WGSL assumes that the render pipeline has already indexed into the array and selected the element to pass it.

It turns out that Metal vertex shaders can also accept an already-fetched `v_in` the way our WGSL does. Here's Naga's translation of that WGSL into Metal (produced by the command `naga ex.wgsl ex.metal`):

```
// language: metal1.0
#include <metal_stdlib>
#include <simd/simd.h>

using metal::uint;

struct VertexOutput {
    metal::float4 position;
    metal::float4 color;
    metal::float2 texcoord;
};
struct VertexInput {
    metal::float4 position;
    metal::float3 normal;
    metal::float2 texcoord;
};
struct type_5 {
    float inner[4];
};
struct LightDesc {
    uint num_lights;
    type_5 light_position;
    type_5 light_color;
    type_5 light_attenuation_factors;
};
constant uint MAX_LIGHTS = 4u;

metal::float4 do_lighting(
    metal::float4 position,
    metal::float3 normal,
    LightDesc light_desc
) {
    return metal::float4(0.0);
}

struct render_vertexInput {
    metal::float4 position [[attribute(0)]];
    metal::float3 normal [[attribute(1)]];
    metal::float2 texcoord [[attribute(2)]];
};
struct render_vertexOutput {
    metal::float4 position [[position]];
    metal::float4 color [[user(loc0), center_perspective]];
    metal::float2 texcoord [[user(loc1), center_perspective]];
};
vertex render_vertexOutput render_vertex(
  render_vertexInput varyings [[stage_in]]
, constant metal::float4x4& mvp_matrix [[user(fake0)]]
, device LightDesc const& light_desc_1 [[user(fake0)]]
) {
    const VertexInput v_in = { varyings.position, varyings.normal, varyings.texcoord };
    VertexOutput v_out = {};
    metal::float4x4 _e5 = mvp_matrix;
    v_out.position = v_in.position * _e5;
    LightDesc _e11 = light_desc_1;
    metal::float4 _e12 = do_lighting(v_in.position, v_in.normal, _e11);
    v_out.color = _e12;
    v_out.texcoord = v_in.texcoord;
    VertexOutput _e15 = v_out;
    const auto _tmp = _e15;
    return render_vertexOutput { _tmp.position, _tmp.color, _tmp.texcoord };
}
```

Going over those three bullet points again:

- Naga has turned the WGSL globals `mvp_matrix` and `light_desc` into arguments to the Metal entry point.

- It's decided to return the `VertexOutput` as the function's return value, like the WGSL; I guess Metal lets you do this either way.

- This output *still* receives only a single vertex data element as its argument, like the WGSL. It introduces a temporary `varyings` argument of a new type `render_vertexInput`, and then rebuilds a `v_in` local variable of the appropriate type at the top of the function. I can't remember why we go through this intermediate step, but by the time we get to the body of `render_vertex`, it has the single element `v_in` to work with.

So what I think we want to do for this issue is to change Naga to translate that WGSL into Metal that, instead of having an argument with the `[[stage_in]]` attribute that accepts a single element like the Naga Metal output immediately above, works more like the first Metal example above, accepting *the entire array* of `VertexInput` structs, along with a new synthetic `[[vertex_id]]` argument, and indexing into the array itself and applying appropriate bounds checks, before proceeding with `render_vertex` as normal.

In other words, Metal permits both styles of vertex shaders, as shown in the first and second Metal examples above. We want to shift Naga from generating the second style of code, where the pipeline does the indexing for us, to generating the first style, so that we can apply bounds checks in the process of doing the indexing into the buffer ourselves.

**Comment by bradwerth** [comment]
Thanks @jimblandy for this detail. This increases my understanding. For now, I have one new question:
1) Is there an *existing* safety issue? What's an example of wgsl that our current translation would turn into unsafe msl? I can sort of see how doing this vertex pulling optimization incorrectly could *create* a safety issue -- maybe differently-sized vertex and attribute buffers trying to be run off the same index -- which we'd need to guard against with the aforementioned bounds checks.

**Comment by jimblandy** [comment]
The WGSL shown above is unsafe on Metal, when used with an indexed draw call whose index buffer contains bad indices. Metal receives the MSL translation shown above, says, "Oh, you are expecting me to fetch the vertex data for you", and just smooshes in code to index into the buffer with the `[[vertex_id]]` value, which it blindly trusts to fall in bounds, in order to produce the `varyings` argument to the `render_vertex` entry point.

But since it's an indexed draw call, that `[[vertex_id]]` value was just something fetched directly from the index buffer, and it could be anything.

**Comment by bradwerth** [comment]
Yes, that makes sense, but it looks like the current translation of wgsl-to-msl doesn't use the `[[vertex_id]]`. It *will*, when we add this performance improvement, but it doesn't do it now. Is there unsafety coming from the Metal `drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:` call? Like since the documentation for that call doesn't say anything about OOB index values, that we assume the driver will do unsafe things?

**Comment by bradwerth** [comment]
> Yes, that makes sense, but it looks like the current translation of wgsl-to-msl doesn't use the `[[vertex_id]]`. It _will_, when we add this performance improvement, but it doesn't do it now. Is there unsafety coming from the Metal `drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:` call? Like since the documentation for that call doesn't say anything about OOB index values, that we assume the driver will do unsafe things?

@kvark is the `drawIndexed` call fundamentally unsafe? Or are we just vulnerable if we implement vertex pulling without adequate OOB checks?

**Comment by cwfitzgerald** [comment]
> call fundamentally unsafe

Yes - the driver is allowed to assume that all the indices are in bounds and omit any internal bounds checks.

**Comment by jimblandy** [comment]
> Like since the documentation for that call doesn't say anything about OOB index values, that we assume the driver will do unsafe things?

What @cwfitzgerald said. Metal just assumes that all the indices in the index buffer are good. WGSL can't make that assumption. So Naga has to translate WGSL vertex shader entry points into Metal Shading Language entry points that take a `[[vertex_id]]`, clamp it to fall in bounds, and then use that as the index into the vertex buffers.
