### ISSUE TITLE
Failed to find adapter on Dx12

### ISSUE THREAD

**Issue by madmaxio** [gfx-rs/wgpu#2437]
I have vmware based virtual machine with win 10/ Dx12 driver, wgpu can't find any adapter both native and on the web. Also I have dx-diag output.

```
[2022-01-29T19:52:12Z WARN  wgpu_hal::dx12::instance] Unable to enable D3D12 debug interface: 0x887A002D
[2022-01-29T19:52:12Z WARN  wgpu_hal::dx12::instance] Unable to enable DXGI debug interface: 0x887A002D
[2022-01-29T19:52:12Z INFO  wgpu_hal::dx12::instance] Failed to cast DXGI to 1.6: 0x80004002
[2022-01-29T19:52:12Z WARN  wgpu_hal::dx12::adapter] Device creation failed: 0x887A0004
[2022-01-29T19:52:12Z WARN  wgpu_hal::dx12::adapter] Device creation failed: 0x887A0004
thread 'main' panicked at 'Failed to find an appropriate adapter',src\main.rs:58:10
```

**Comment by kvark** [comment]
Your DX12 doesn't support even Feature Level 11_0. We can't reasonably run on it, sorry!
Updating your OS may help.
Getting DX11 in #2443 would also solve this.

**Comment by madmaxio** [comment]
This means wgpu works fine with DX12, but I need latest update for DX12?

**Comment by CatCode79** [comment]
Updating drivers is almost always a good idea, but in this case I think the problem is more particular and related to virtualization.
I haven't used a vmware machine in a long time, but I think you can proceed with these attempts:

- in case you do not already do a search of all the adapters to get a clear idea if even if the wgpu does not find an adapter at least someone visible you have it on the vmware ([poll_all method here](https://docs.rs/wgpu/latest/wgpu/struct.Instance.html#method.poll_all))
- i have no idea how vmware can communicate with the gpu, but it might have a software layer, in this case it might be an idea to play with the [force_fallback_adapter](https://docs.rs/wgpu/latest/wgpu/struct.RequestAdapterOptionsBase.html#structfield.force_fallback_adapter) option
- you may have to force a passthrough of your gpu on your vmware: [like this](https://virtualizationreview.com/articles/2020/05/04/graphics-cards-vms.aspx)

**Comment by madmaxio** [comment]
I see drivers are pretty old, will try to update them to make things clear.
