### ISSUE TITLE
Push constants in render bundles are half-implemented

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#2683]
`RenderBundleEncoder::finish` propagates `SetPushConstant` commands from the encoder to the final `RenderBundle`, but the bundle's `BasePass`'s `push_constant_data` vector is always empty.

**Comment by jimblandy** [comment]
Note that push constants are not yet specified in WebGPU: gpuweb/gpuweb#75

**Comment by simonask** [comment]
Coming up on the 2-year anniversary for this issue, are there any current plans to support this? If nothing else, it would probably be good to catch any use of push constants in `RenderBundleEncoder`, rather than crashing at (potentially much later) point in time. Potentially by removing the `set_push_constants` method altogether until this is actually implemented. :-)

**Comment by cwfitzgerald** [comment]
I don't think this is on anybody's radar right now, so we'd accept a PR either fixing it, or removing it.
