### ISSUE TITLE
Change `get_preferred_format` to `get_supported_formats`

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#2718]
**Is your feature request related to a problem? Please describe.**

There's currently no way to actually get the full list of supported surface textures.

**Describe the solution you'd like**

Turn 

```rust
Surface::get_preferred_format(&self, adapter: &Adapter) -> TextureFormat
```

into

```rust
Surface::get_supported_formats(&self, adapter: &Adapter) -> Vec<TextureFormat>
```

which will always return the "preferred" format first.

**Describe alternatives you've considered**

Having both calls be independent.

**Comment by cwfitzgerald** [comment]
@Kangz this one also has potential ramifications in webgpu-native.

**Comment by Kangz** [comment]
Having a preferred format would help, since that matches the Web API and on each platform there are actual preferred formats. In the spirit of strong portability of WebGPU, I think there should be some set of formats that is guaranteed to be supported even if it incurs a blit. So we should have an API to say what is THE preferred format (for SDR/HDR??), what formats are fast, and what are supported.
