### ISSUE TITLE
validation errors on dynamic stencil after gfx 0.3

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#279]
Updating to latest wgpu-rs, which is upgrades to gfx 0.3, I am seeing this validation error printed every frame:

```
[2019-08-12T05:08:59Z ERROR gfx_backend_vulkan] 
VALIDATION [VUID-vkCmdDraw-commandBuffer-02701 (0)] : VkCommandBuffer 0x555e82891100[]: Dynamic stencil reference state not set for this command buffer.. The Vulkan spec states: If the VkPipeline object bound to the pipeline bind point used by this command requires any dynamic state, that state must have been set for commandBuffer (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdDraw-commandBuffer-02701)
object info: (type: COMMAND_BUFFER, hndl: 93864405307648)
```
I'm not sure what this means exactly; but I don't think I need to change anything new at the api level ?

**Comment by rukai** [comment]
That will probably be due to how I upgraded wgpu to gfx 0.3 I'll look into it.

**Comment by kvark** [comment]
We specify the stencil references to be dynamic [here](https://github.com/gfx-rs/wgpu/blob/f72dfc9cbbcf752ea5905ff9b038f8ca3f1d3691/wgpu-native/src/conv.rs#L249). It only happens when there is an actual depth-stencil state provided, and I don't think we validate the `set_stencil_reference` function against the current pipeline yet (which might be hitting your case).
[Here is](https://github.com/gfx-rs/gfx/blob/3c323be338b478b9b2a207f1d39c39dafb8d1979/src/backend/vulkan/src/device.rs#L694) where gfx sees our `Dynamic` state and registers `vk::DynamicState::STENCIL_REFERENCE` with Ash.

**Comment by kvark** [comment]
Seeing this now, investigating...
