### ISSUE TITLE
"Not enough memory left" when creating a bind group with too many textures / samplers (DX12)

### ISSUE THREAD

**Issue by hasenbanck** [gfx-rs/wgpu#2857]
For a bindless sprite engine we use the texture binding array feature and bind each texture with the sampler that the texture is using in one bind group. 

When creating a bind group with more than 1025 textures and 1025 samplers in an array, the current DX12 backend (0.13.1) will throw the following error:

```
Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `XXX Bind Group`
    not enough memory left

Location { 
    file: "C:\\Users\\XXX\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\wgpu-0.13.1\\src\\backend\\direct.rs",
    line: 2391,
    col: 5
}
```

Following features are used:
TEXTURE_BINDING_ARRAY
SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING

Following limits are set:
max_samplers_per_shader_stage = 1800
max_sampled_textures_per_shader_stage = 1800

The Vulkan backend works fine. The DX12 backend will also work fine with 1024 textures / samplers each.

Creating two bind groups, one for the 1025 textures and one for the 1025 samplers each will not fix the problem and result in the same error.

I would at least expect WGPU to panic when checking the limits of the device or better, to not have this limitation at all (but I don't know if this is a DX12 limitation or a limitation of the WGPU DX12 backend).

**Comment by hasenbanck** [comment]
2048 would be fine, since the main limiting factor on Vulkan currently are Intel devices, which have a sampler limit of 1800 on most devices.

The question now is, where do the other 1024 sampler go?
I also think that this limit should also be validated against.

**Comment by norepimorphism** [comment]
> The question now is, where do the other 1024 sampler go?

The way I see it, there are a few possibilities:
1. the sampler descriptor heap is only allocated with a capacity of 1024;
2. some or all samplers consume more than one descriptor;
3. the range allocator fails due to memory fragmentation;
4. *wgpu* or *range-alloc* fail in some other way;
5. your code creates the bind group twice; or
6. prior to the creation of the bind group in question, your code already allocated 1024 sampler descriptors.

## 1. The sampler descriptor heap is only allocated with a capacity of 1024

AFAICT, *wgpu* does this correctly. The sampler descriptor heap is allocated here:
https://github.com/gfx-rs/wgpu/blob/e49ef973111265eb4f6de65a75ee701a90cfa4fb/wgpu-hal/src/dx12/device.rs#L121-L125

...where `capacity_samplers` was previously defined to be 2048. The other end of this call is here:
https://github.com/gfx-rs/wgpu/blob/e49ef973111265eb4f6de65a75ee701a90cfa4fb/wgpu-hal/src/dx12/descriptor.rs#L38-L68

`capacity_samplers` has been renamed to `total_handlers` and is used to construct `ranges`, the range allocator. I have briefly looked over the *range-alloc* crate and assume it is correct as many things would probably break horrifically if it wasn't.

## 2. Some or all samplers consume more than one descriptor

The journey of a DX12 sampler descriptor begins here:
https://github.com/gfx-rs/wgpu/blob/e49ef973111265eb4f6de65a75ee701a90cfa4fb/wgpu-hal/src/dx12/device.rs#L1184-L1190

This code lies within a `for` loop that iterates over each entry of a bind group descriptor. For each sampler entry, one or more handles are appended to this `stage` field. To hazard a guess, I think 'normal' sampler entries produce only one handle, while sampler arrays may produce one or more.

There is a potential for error here. If `entry.count` is greater than one for a singular sampler entry, then more sampler descriptors will be allocated than were requested. However, I would think `entry.count` is determined by the *wgpu* crate rather than *wgpu-hal*, so such an error *shouldn't* selectively affect DX12. (I should check this to be sure.)

Moving on, the aforementioned `stage` field is consulted here:
https://github.com/gfx-rs/wgpu/blob/e49ef973111265eb4f6de65a75ee701a90cfa4fb/wgpu-hal/src/dx12/descriptor.rs#L291-L309

Its length is passed to `allocate_slice` directly, so everything looks good there. If there were 1025 sampler entries, then a slice with length 1025 should have been allocated.

## 3. The range allocator fails due to memory fragmentation

Assuming only one bind group is ever created, this seems unlikely as all 1025+ sampler descriptors are created simultaneously and thus occupy a contiguous memory range.

<hr>

I'll continue looking at this tomorrow.

**Comment by norepimorphism** [comment]
W.r.t `entry.count`, it is determined in *wgpu-core* here:
https://github.com/gfx-rs/wgpu/blob/e49ef973111265eb4f6de65a75ee701a90cfa4fb/wgpu-core/src/device/mod.rs#L1840-L1885

LGTM. It does some checks before returning `(res_index, 1)` where 1 is used to initialize `wgpu_hal::BindGroupEntry::count`. So, only one sampler descriptor is ever allocated per sampler specified in the bind group descriptor.

**Comment by cwfitzgerald** [comment]
Closing in favor of #3350, if there's anything that doesn't cover, shout.
