### ISSUE TITLE
Dependency Reduction?

### ISSUE THREAD

**Issue by AldaronLau** [gfx-rs/wgpu#2861]
I was looking at cargo tree and wondering if there's places for improvement in reducing dependencies.  I came up with the following things:

 - I'm wondering if it's possible to make raw-window-handle an optional dependency (say if the programmer doesn't need a window).
 - Dependencies naga and codespan-reporting always pull in termcolor, which should be unnecessary
 - The smallvec and arrayvec dependencies do *almost* the same thing, could possibly use tinyvec for both use cases
 - The profiling crate could also be optional

I don't know if all of these are a good idea, but I'd be willing to work on any of them.

**Comment by kpreid** [comment]
These two are probably only relevant if wanting to remove dependency *count* rather than size:

* `raw-window-handle` is very lightweight since it only provides types (that contain `*mut c_void` pointers for the most part).
* `profiling` only depends on profiling backends requested by features — its purpose is essentially to *be* the mechanism by which profiling instrumentation is conditionally compiled.

**Comment by cwfitzgerald** [comment]
Smallvec is a much more complicated bit of kit - it has non-zero overhead over a Vec/ArrayVec, so it's a specialized tool that we need in certain situations.

**Comment by teoxoy** [comment]
`codespan-reporting` (used in wgpu to display naga's validation errors) depends on `termcolor`, so making naga's usage of `termcolor` optional won't change wgpu's tree.

I double checked wgpu's tree and it seems besides https://github.com/gfx-rs/wgpu/pull/3502 there aren't other opportunities to remove other dependencies.

I think we can close this for now.
