### ISSUE TITLE
Expose readonly size/usage on wgpu::Buffer

### ISSUE THREAD

**Issue by swiftcoder** [gfx-rs/wgpu#2904]
**Is your feature request related to a problem? Please describe.**

Per the draft spec, it appears that GPUBuffer is supposed to expose it's size and usage via readonly properties:
https://gpuweb.github.io/gpuweb/#buffer-interface

As of wgpu-rs 0.13.1, on the rust side neither of these properties are currently visible to application code. Also the wgpu::Buffer type doesn't appear to be caching the size at all.

**Describe the solution you'd like**

Keep a cached copy of the size on wgpu::Buffer, and expose member functions to provide readonly access to both the size and usage fields.

**Describe alternatives you've considered**

The application can always track these attributes externally, since they are immutable after construction, but I'd hate to permanently incur that added burden on application code.

**Comment by kpreid** [comment]
I've heard that WebGPU and/or `wgpu` intentionally don't provide “getters” for most state, so that the data flow is primarily CPU-to-GPU without ever pausing to fetch data back or requiring wgpu to speculatively retain information in case it is needed.

However, buffer sizes would be especially useful, because whenever a buffer has dynamically sized contents, it may be useful to understand the buffer's size as a “capacity” (in the sense of `Vec::capacity()`), potentially use less than all of the buffer, and consult the size to determine whether allocating a new buffer is necessary.

**Comment by swiftcoder** [comment]
>  and consult the size to determine whether allocating a new buffer is necessary.

Yep, that's exactly the case I'm running into. I have an unpredictable number of mesh instances, and the instance data buffer sometimes needs to grow to accommodate additional instances
