### ISSUE TITLE
Should wgpu pad to 16 bytes automatically?

### ISSUE THREAD

**Issue by simbleau** [gfx-rs/wgpu#2932]
Maybe a bit of an opinion, but I consider this a fun surprise to newcomers.

[This issue in Bevy outlines it.](https://github.com/bevyengine/bevy/issues/5393)

When compiling for WASM, if you do not pad your data blobs to 16 bytes then a validation error gets thrown, forcing you to pad to 16.

> wasm.js:407 panicked at 'wgpu error: Validation Error
> 
> Caused by:
>     In Device::create_render_pipeline
>       note: label = `opaque_mesh_pipeline`
>     Downlevel flags BUFFER_BINDINGS_NOT_16_BYTE_ALIGNED are required but not supported on the device.
> This is not an invalid use of WebGPU: the underlying API or device does not support enough features to be a fully compliant implementation. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to work around this issue, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.

Would it not be possible to do a memory size check and add padding for the user?
I guess it boils down to whether this is a significant performance sacrifice.

**Comment by grovesNL** [comment]
Great question! It would be great if we could make this easier.

I'm not sure if there's a good way to automatically pad, because we're reading from part/all of a buffer provided by the caller. That buffer would have to be modified, which might not be possible depending on how its used (e.g., copying and padding might not be possible).

There's some similar discussion in Chromium/ANGLE at https://bugs.chromium.org/p/chromium/issues/detail?id=988988#c11 where the restriction comes from originally, where the fix was to require 16-byte alignment instead of automatically padding

**Comment by cwfitzgerald** [comment]
Yeah I don't think we can pad in any valid way that doesn't potentially stomp on user data.
