### ISSUE TITLE
`Instance::enumerate_adapters` is missing on wasm and this is not documented

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#3089]
**Description**

I was surprised to receive this error after refactoring to move some initialization code into a common library:

```
error[E0599]: no method named `enumerate_adapters` found for struct `wgpu::Instance` in the current scope
```

Examining the source code reveals that `Instance::enumerate_adapters` is conditionally compiled for ((not wasm32) or emscripten).

**Expected vs observed behavior**
Either the absence should be mentioned in the API documentation, or it should be available even if it only returns one low-information result — preferably the latter, so that cross-platform code is easier.

**Platform**
macOS (cross-compiling to wasm32-unknown-unknown with wasm-bindgen)
wgpu 0.14.0

**Comment by grovesNL** [comment]
If possible, `request_adapter` should generally be preferred over `enumerate_adapters` because it's always available.

`enumerate_adapters ` currently isn't implementable on the web backend without changing the API to return a future of `Vec<AdapterId>` because it would have to use `request_adapter` internally.

For now we could at least add the note that `enumerate_adapters` isn't available on the web backend, and maybe consider changing the signature afterwards.

**Comment by cwfitzgerald** [comment]
This is now documented.
