### ISSUE TITLE
Unable to initialize adapter when launched through renderdoc on Vulkan + Wayland

### ISSUE THREAD

**Issue by CatThingy** [gfx-rs/wgpu#3127]
**Description**
wgpu is unable to initialize a GPU adapter when lauched through renderdoc on Vulkan + Wayland

**Repro steps**
Build one of the examples (I chose boids).
Attempt to launch the example binary through renderdoc, setting the environment variables `WGPU_BACKEND=vulkan` and `WINIT_UNIX_BACKEND=wayland`
Note that launching with either `WGPU_BACKEND=gl` or `WINIT_UNIX_BACKEND=x11` works as expected.

**Expected vs observed behavior**
I expected the example to launch with renderdoc attached.
Instead, it panics with `thread 'main' panicked at 'No suitable GPU adapters found on the system!', wgpu/examples/boids/../framework.rs:184:14`

**Extra materials**
N/A
**Platform**
Arch Linux x86_64 6.0.2-arch1-1
Integrated graphics on the AMD Ryzen 7 4700U
Vulkan drivers from mesa

**Comment by cwfitzgerald** [comment]
This is actually intended behavior. Renderdoc doesn't support wayland, so the renderdoc later removes the wayland surface extension from the extension list. Because we can't make and adapter compatible with that surface without the extension, you get no adapter.

The solution is to always run in x11 mode with renderdoc.
