### ISSUE TITLE
"No work has been submitted for this frame" timeout

### ISSUE THREAD

**Issue by Beyley** [gfx-rs/wgpu#3189]
**Description**
If you do not submit any work for a surface, and present it, problems occur running wgpuSwapChainGetCurrentTextureView (wgpu-native), it seems to be hitting [this line](https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/present.rs#L314) specifically

**Repro steps**
You can just strip out all code that submits work from any rendering example

**Expected vs observed behavior**
Nothing should happen, and wgpuSwapChainGetCurrentTextureView should run just fine, but it does not, sometimes failing with a timeout, sometimes working 

**Extra materials**
the 'beginning scene' is where i get the swap chain's current texture view, things marked with 'CallbackError' are errors from wgpuDeviceSetUncapturedErrorCallback
![image](https://user-images.githubusercontent.com/34501060/200480514-45f49ddd-ebc2-4200-b3c8-28435236e9ad.png)

**Platform**
Arch Linux, AMD GPU, latest master of wgpu-native

**Comment by teoxoy** [comment]
I don't really understand why we need the `has_work` flag. Mapping `!has_work` to `SurfaceError::Outdated` doesn't seem ideal. Does presenting a surface that hasn't changed cause any issues?

#1892 (PR that introduced the flag) mentiones:

> Adds `has_work` flag to surface textures. This is temporary, until #1688 takes a better care of it.

Considering #1688 has been merged, can we get rid of `has_work` and just present the surface?

@cwfitzgerald do you have more context for this (since you reviewed #1892)?
