### ISSUE TITLE
Undocumented panic when creating buffer not of size mod 4

### ISSUE THREAD

**Issue by 4LT** [gfx-rs/wgpu#3219]
May or may not be a bug, but creating an index buffer that's mapped at creation with a size not divisible by 4 causes a panic
```
Caused by:
    In Device::create_buffer
      note: label = `vertex_index_buffer`
    buffers that are mapped at creation have to be aligned to `COPY_BUFFER_ALIGNMENT`
```
This behavior is not documented under either `create_buffer` or `BufferDescriptor` documentation.

If this *is* intended behavior, would it be possible (or reasonable) to pad out the buffer's allocation to fit the alignment?  E.g. I want 81 Uint16 indices, so add an extra 2 bytes on to the allocation, but only leave the first 162 bytes usable.

## Platform
Arch Linux 6.0.2
Radeon RX 5600 XT
~~Forgot what the driver is (amdgpu? what's the Vulkan equivalent of glxinfo?)~~ RADV

**Comment by nical** [comment]
You are seeing a validation error which follows the [webgpu specification](https://gpuweb.github.io/gpuweb/#dom-gpudevice-createbuffer). It turns into a panic because that's the default handler behavior for uncaught validation errors. As far as documentation goes I encourage you to use the webgpu spec as the primary source of truth, since wgpu is meant to match exactly that, even in places where the implementation and/or doc aren't fully there yet.

I don't think wgpu should take extra steps beyond WebGPU's documented behavior. You can easily pad out the buffer allocations on your side (in fact in order to comply with the specification, validation has to raise an error if a buffer size isn't a multiple of 4).
