### ISSUE TITLE
implementing default for more instances, devices, etc...

### ISSUE THREAD

**Issue by nilsmartel** [gfx-rs/wgpu#3298]
**Is your feature request related to a problem? Please describe.**
Code can be quite verbose and sensible defaults are elusive for newcomers

**Describe the solution you'd like**
Implement std::default::Default for more Instance, Adapter, etc.

**Describe alternatives you've considered**
I think sensible defaults should be implemented using the Default trait,
the alternative is the current state of things.
(e.g. using Backends::all() directly etc.)

**Comment by cwfitzgerald** [comment]
What kinds of implementations are you looking for? Instance doesn't have a descriptor (yet), so can't impl default. Adapter could, maybe defaulting to high power (as if you need low power, you should know what you're doing).

**Comment by nilsmartel** [comment]
> as if you need low power, you should know what you're doing

Yeah, things like these are what I'd consider.
Now the sort of compass I would like to follow here is giving newbies (Like myself, Hi!!) as quickly as possible what they came for: Computer Power! :)


As someone who's very uninformed about the gpu space yet, I think I might have some misconceptions, but I think something like this:
```rust
struct Gpu {
    queue: Queue,
    device: Device,
}

impl Default for Gpu {
    fn default() -> Self {
        let instance = Instance::new(Backends::all());
        // get adapter (physical device)
        let adapter = instance
            .request_adapter(&RequestAdapterOptions::default())
            .await
            .unwrap();

        dbg!(adapter.get_info());

        // get device (logical device)
        let (device, queue) = adapter
            .request_device(&DeviceDescriptor::default(), None)
            .await
            .unwrap();

        Gpu { queue, device }
    }
}
```

is a fairly standard shorthand that might already help people not being scared so easily :)

**Comment by kpreid** [comment]
Specific concern: High power is a bad default. Specifically, it is convenient and “just works” for developers — and imposes its cost on users of the software (energy consumption). If there is to be a default, the default should be low power, so that if high power is needed it becomes obvious in testing.

Vague concern: I think hiding all the initialization behind one `Default` implementation would also be a “bad default” because it hides how many choices are being made. (Any application wishing to be webgl2 or GLES compatible needs to change the device descriptor defaults.) Also, `Gpu::default()` would have to block on the async `request_*`.

**Comment by nilsmartel** [comment]
> Also, Gpu::default() would have to block on the async request_*.

yeah, I vaguely ignored this concern, because I couldn't solve it.
Maybe not use the actual Default trait, but keep the lingo, because rustaceans are familiar with it? Oh I hope thats not accidentally a super-bad-practice. (see below for another advantage of this though)

> and imposes its cost on users of the software (energy consumption)

oi, that's a rightful concern.
Let me clarify, what is my desired outcome:

People get to have the max gpu power to play with immediately, making the dip into (gp)gpu easier and more rewarding!

Now, on the same page I want people to quickly see, how these default came to be, using "go to definition".
Using the default trait would make people see the definition of the default page, when using "go to definition" shorthands in their editors. So using that trait might defeat the purpose of my desired outcome.

I'd love to make the starting point more accessible and details easier to find :)

But then, yeah. Low power makes sense, though it can be demotivating for the programmer at hand I think.

Does anyone know what CUDA does in this case? I heard (know that my knowledge is very limited) it employs a lot of "sane defaults" to guide the user expirience

**Comment by kpreid** [comment]
Just remembered something I should have mentioned: the [`wgpu::util`](https://docs.rs/wgpu/latest/wgpu/util/index.html) module has a bunch of functions for initializing based on environment variables or defaults. A good path forward might be to promote those functions more in the documentation (e.g. have `learn-wgpu` use them) (with the caveat noted that they panic on failure and so on!) and add a function to that family that gets you a `Device` &amp; `Queue` rather than only an `Adapter`.

**Comment by nilsmartel** [comment]
I would love that!
For me, documentation in form of tutorials feels close to my heart.
Again, it's something especially beginners can benefit from a lot.

The util module is something I have scarecly been aware of. This may (or may not) be an indicator, that it's a little hidden.

but writing some utils aimed at beginners, that could be really cool :)

**Comment by cwfitzgerald** [comment]
I'm not sure how much we as wgpu can really help with this, as we need to stay generic enough for people to do whatever they need.
