### ISSUE TITLE
LoadOp::Clear values do not make sense for non-RGBA texture formats

### ISSUE THREAD

**Issue by torsteingrindvik** [gfx-rs/wgpu#3302]
**Is your feature request related to a problem? Please describe.**
Problem: When describing a `RenderPassColorAttachment` `LoadOp::Clear` operation, a color is expected.
I am rendering to a texture with format `R32Uint`, it is therefore not intuitive how I can set this to a value I want since the color must be specified in RGBA.

**Describe the solution you'd like**
Honestly I'm not quite sure, but perhaps a format-aware way to specify values?

**Describe alternatives you've considered**
Dealing with the current API.
I'm using Bevy, and specifying:

```rust
Color::Rgba {
    red: f32::MAX,
    green: f32::MAX,
    blue: f32::MAX,
    alpha: f32::MAX,
}.into()
```

Does indeed turn into `u32::MAX` as the clear value like I wanted.

**Comment by Wumpf** [comment]
This follows the WebGPU spec which defines a conversion function for the passed color function
https://www.w3.org/TR/webgpu/#abstract-opdef-to-a-texel-value-of-texture-format

which in turn is this way because that's what clear values in most graphics apis look like. Sure, it's not exactly intuitive and when doing a rust-first api this could be an enum, but wgpu first and foremost models WebGPU

**Comment by torsteingrindvik** [comment]
Ok, that's understandable. Thanks for the info.
Perhaps this is not actionable here then? Feel free to close this issue if so.

Since Bevy re-exports wgpu stuff I could perhaps persuade them to have a thin layer which could turn into `wgpu::Color`.
