### ISSUE TITLE
WGPU version 15 not starting

### ISSUE THREAD

**Issue by Norlock** [gfx-rs/wgpu#3442]
**Description**
I have updated wgpu to version 15, but my project won't start now. 

**Repro steps**
```shell
git clone https://github.com/Norlock/sparticles/tree/version-15
cargo run --release --example default
```

**Expected vs observed behavior**
Expected: either an error or successful start
Observed: no window is being opened.

**Platform**
WGPU version: 15
Linux:  Arch

**Comment by nical** [comment]
There is not very much to go on. Here are a number of steps and informations to collect that you can do to help move this forward:
 - Find out whether app is frozen and if so, where (for example using `gdb` to see what is going on)
 - Detailed hardware and driver inforomation (you can get that and more by running `vulkaninfo`)
 - Do the examples in the wgpu repository run?
 - If not a link to the code so that someone can reproduce the issue, or a reduced test case.
 - Bisecting wgpu commits to find what commit introduced the regression.

**Comment by Norlock** [comment]
Yes it was my fault, I debugged and commented out some code :/.
