### ISSUE TITLE
gl_vertexID variable from converting from wgsl to glsl vertex shader received in naga, which is not compilable by wgpu

### ISSUE THREAD

**Issue by Trap101** [gfx-rs/wgpu#3831]
When I try to convert the vertex part of the example wgsl shader from [learn wgpu tutorial](https://sotrh.github.io/learn-wgpu/beginner/tutorial3-pipeline/#writing-the-shaders) through Naga, I got this
```
#version 450 core
struct VertexOutput {
    vec4 clip_position;
    vec4 color;
};
layout(location = 0) smooth out vec4 _vs2fs_location0;

void main() {
    uint in_vertex_index = uint(gl_VertexID);
    VertexOutput out_ = VertexOutput(vec4(0.0), vec4(0.0));
    float x = (float((1 - int(in_vertex_index))) * 0.5);
    float y = (float(((int((in_vertex_index & 1u)) * 2) - 1)) * 0.5);
    out_.clip_position = vec4(x, y, 0.0, 1.0);
    vec4 _e24 = out_.clip_position;
    out_.color = _e24;
    VertexOutput _e25 = out_;
    gl_Position = _e25.clip_position;
    _vs2fs_location0 = _e25.color;
    gl_Position.yz = vec2(-gl_Position.y, gl_Position.z * 2.0 - gl_Position.w);
    return;
}


```
which seems fine, except gl_vertexID is not a valid token that can be read by naga. And this cannot be passed through `wgpu` to be converted into valid draw call, as, well `gl_VertexID` according to the source code, is not valid, while `gl_VertexIndex` is. 
So i am not sure if this is a rendering side of an issue from wgpu? or a compiling side issue from naga. But this is quite strange to me.
this is the error message
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: [Error { kind: UnknownVariable("gl_VertexID"), meta: Span { start: 185, end: 196 
} }]',
```
Even if I try to use gl_VertexIndex in my own shader code, it still seems to fail, I don't know why.
here is the proof of concept vertex shader
```
#version 450
layout(location = 0) out vec3 frag_color;
void main(){
    vec2 pos[3] = vec2[3]( vec2(-0.7, 0.7),
                           vec2(0.7, 0.7),
                           vec2(0.0, -0.7) );
    gl_Position = vec4( pos[uint(gl_VertexIndex)], 0.0, 1.0 );
    frag_color = color;
}
```
fragment shader
```
#version 450
layout(location = 0) in vec3 frag_color;
layout(location = 0) out vec4 outColor;
void main(){
   outColor = vec4(frag_color,1.0);
}
```
this does not render anything, and i have tried passing in vertex and index buffer, they work just fine, is this a naga issue, or a rendering issue from wgpu? or did i do something terribly wrong?

**Comment by Wumpf** [comment]
You seem to try to ingest GLSL code that was generated from Naga to wgpu. That doesn't really make sense though, sounds like you got a little bit confused or I'm not understanding what you're trying to achieve :)
Either you write GLSL code by hand for a native wgpu application and pass it in via [wgpu::ShaderSource::Wgsl](https://docs.rs/wgpu/latest/wgpu/enum.ShaderSource.html) or you pass the wgsl code directly.

`gl_VertexIndex` does not exist in any shading language, what made you conclude that's what it should be?

**Comment by Trap101** [comment]
Well, I looked at naga's source of passing GLSL and WGSL, and apparently, `@builtins(vertex_index)` gets passed in as `Builtins::VertexIndex `which, when I have a look at the GLSL backend, the corresponding one was `gl_VertexIndex`, I passed it in and there were no errors, so I suppose I was being extra naive and thought that must have been the right answer.
My problem is basically that `gl_VertexID` don't seem to be recognised, and reports me an error while `gl_VertexIndex` gets pass in just fine, yet that is apparently nothing, and doesn't exist, is there a GLSL version of `@builtins(VertexIndex)` that I am not aware of or more of a bug?

**Comment by Wumpf** [comment]
Alright my comment  regarding `gl_VertexIndex` was not 100% accurate and a more about my assumption of what you're trying to do: `gl_VertexIndex` is valid for GLSL targeting SpirV, but GLSL as consumed by OpenGL directly doesn't define that. So either will work depending on the target. When passing in raw Glsl to wgpu it treats that as OpenGL  targed and uses Naga only for validation, not conversion, so afaik it complains about `gl_VertexIndex` because that doesn't make sense for OpenGL.
Naga's GLSL output makes sense in that far that the usecase of its Glsl backend is to be used by OpenGL and not as an input for SpirV generation. 
`gl_VertexID` _should_ be recognized if you have a GLSL shader that is intended for *pass-through to OpenGL*, i.e. without any conversion (is that what you're trying to do?). I that isn't the case, there is indeed a bug in Naga or how that Glsl shader is passed to Naga (wgpu will still give every shader to Naga for validation purposes)

**Comment by teoxoy** [comment]
See @cwfitzgerald's answer in https://github.com/gfx-rs/naga/issues/2369#issuecomment-1575967860
