### ISSUE TITLE
AMD on DX12 Renders Nothing on `msaa-line` Example

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#3838]
It literally renders a transparent image.

**Comment by Elabajaba** [comment]
It renders properly on my system (AMD + DX12).

**Comment by cwfitzgerald** [comment]
I should have clarified, this is in the test, does `cargo nextext run` with dx12 report an unexpected success?

**Comment by Elabajaba** [comment]
It does.

fun

edit: Are the comparisons `screenshot.png` (the base), `screenshot-dx12-actual.png` (what the test renders?) `screenshot-dx12-difference.png` (the difference between base and test render?) in `wgpu\examples\msaa-line`? (or I guess now `examples\msaa-line\`) Because on my system the dx12 screenshot just looks more anti-aliased.

screenshot-dx12-actual: 
![screenshot-dx12-actual](https://github.com/gfx-rs/wgpu/assets/177631/9b93abb8-1f02-4ffd-8c54-b57de920ef45)

**Comment by teoxoy** [comment]
Has this been fixed by newer drivers?

**Comment by cwfitzgerald** [comment]
It only reproduced on one GPU that I no longer have access too, and didn't reproduce for others, and only affected tests, so I just closed it

**Comment by teoxoy** [comment]
I see, will mark it as a driver bug then. Do you remember what model it was?

Also, should we remove the expected fail in the test then?

https://github.com/gfx-rs/wgpu/blob/fd53ea90e675d94f1d79a1c3c44b2f356cecd9c5/examples/msaa-line/src/main.rs#L333

**Comment by cwfitzgerald** [comment]
Yeah we should.

RX 580

**Comment by Friz64** [comment]
I have access to a RX 580 and can confirm it is fixed.
