### ISSUE TITLE
Shader translation from SPIR-V fails targeting DX12

### ISSUE THREAD

**Issue by radgeRayden** [gfx-rs/wgpu#3983]
I have previously filed an issue about this for wgpu-native: https://github.com/gfx-rs/wgpu-native/issues/274
I also have an even smaller trace, it's just a very basic shader that indexes into a Storage Buffer. I've extracted the [HLSL output](https://gist.github.com/radgeRayden/a5de943501c964c979bbdfb6672decb1) for convenience, but the complete wgpu trace is below.
[wgpu-trace.txt](https://github.com/gfx-rs/naga/files/11994567/wgpu-trace.txt)

Also the original shader (in SPIR-V form):
[shader.zip](https://github.com/gfx-rs/naga/files/11994569/shader.zip)

**Comment by teoxoy** [comment]
`CreateGraphicsPipelineState` is returning [`E_INVALIDARG`](https://learn.microsoft.com/en-us/windows/win32/direct3d12/d3d12-graphics-reference-returnvalues) which doesn't tell us much.

Could you post the trace of a debug build? We should get more info that way since the D3D12 debug layers are only enabled if `cfg!(debug_assertions)`.

**Comment by radgeRayden** [comment]
> `CreateGraphicsPipelineState` is returning [`E_INVALIDARG`](https://learn.microsoft.com/en-us/windows/win32/direct3d12/d3d12-graphics-reference-returnvalues) which doesn't tell us much.
> 
> Could you post the trace of a debug build? We should get more info that way since the D3D12 debug layers are only enabled if `cfg!(debug_assertions)`.

[wgpu-trace.txt](https://github.com/gfx-rs/naga/files/12167665/wgpu-trace.txt)

(edited with non cutoff log)

**Comment by teoxoy** [comment]
From the log, these are the expected bindings for the Vertex shader:

```
var GlobalVariable { name: Some("input-data"), space: Storage { access: LOAD | STORE }, binding: Some(ResourceBinding { group: 0, binding: 1 }), ty: [6], init: None }
var GlobalVariable { name: Some("uniforms"), space: Uniform, binding: Some(ResourceBinding { group: 0, binding: 0 }), ty: [13], init: None }
```

What are the bindings you are passing to wgpu?

**Comment by radgeRayden** [comment]
> From the log, these are the expected bindings for the Vertex shader:
> 
> ```
> var GlobalVariable { name: Some("input-data"), space: Storage { access: LOAD | STORE }, binding: Some(ResourceBinding { group: 0, binding: 1 }), ty: [6], init: None }
> var GlobalVariable { name: Some("uniforms"), space: Uniform, binding: Some(ResourceBinding { group: 0, binding: 0 }), ty: [13], init: None }
> ```
> 
> What are the bindings you are passing to wgpu?

Uniform Buffer at 0 and Storage Buffer at 1. Like I mentioned (in the other issue), my code works as expected on Vulkan.

**Comment by teoxoy** [comment]
For the storage buffer, is it a `BufferBindingType::Storage { read_only: true }` (i.e. is it read only on the API side)?

**Comment by radgeRayden** [comment]
Currently I am using auto layouts, so it seems like I don't get to set that. The Buffer usage is `wgpu.BufferUsage.Storage | wgpu.BufferUsage.CopyDst | wgpu.BufferUsage.CopySrc`.

**Comment by teoxoy** [comment]
What is happening here is that we derive the layout via how the global is used in the shader instead of how it's declared (in the shader).

https://github.com/gfx-rs/wgpu/blob/8a8e00a5a523311c7576eebf953bcc5ffa56f557/wgpu-core/src/validation.rs#L566

Relevant Spec Text:

![image](https://github.com/gfx-rs/wgpu/assets/28601907/73951c8a-1287-4c31-9184-59f9c3378ed5)

This works fine for all other backends but not the dx12 backend as we will use either an SRV or an UAV for the buffer depending if it's read-only or not.

https://github.com/gfx-rs/wgpu/blob/8a8e00a5a523311c7576eebf953bcc5ffa56f557/wgpu-hal/src/dx12/conv.rs#L105-L114

## Conclusion

- You should add the `NonWritable` SPIR-V decoration to the storage buffer as the vertex stage only supports read-only storage buffers (without the `VERTEX_WRITABLE_STORAGE` wgpu feature enabled), which will in turn avoid the underlying issues and get things running.
- We need to infer the binding type based on how it's declared in the shader instead of how it's used.

**Comment by radgeRayden** [comment]
Unfortunately after adding the `NonWritable` decoration to the buffer, I still get the same error. Maybe our generator is wrong, I can't tell yet (not an SPIR-V expert). Here's the shader disassembly followed by the trace.
[wgpu-trace.txt](https://github.com/gfx-rs/wgpu/files/12188287/wgpu-trace.txt)

**Comment by teoxoy** [comment]
I see that the `NonWritable` decoration got added to the members of `VertexAttributes` and `VertexAttributesBuffer`. While that is allowed by the SPIR-V spec, naga will only take into account `NonWritable` decorations on the variable `input-data` itself.

For reference:

![image](https://github.com/gfx-rs/wgpu/assets/28601907/8948f2a9-8c3e-4e8e-9a07-9452f03822d7)

_from https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Decoration_

**Comment by radgeRayden** [comment]
Thank you, I made the change you suggested and it worked.
