### ISSUE TITLE
MacOS (Metal) Slow performance compared to Linux/Windows (for minimal workload)

### ISSUE THREAD

**Issue by Nazariglez** [gfx-rs/wgpu#4013]
Hey!

I am not sure if this is a bug or not, but I just wanted to ask if this rings a bell or if somebody knows what could be happening.

I am doing some work with wgpu, and I found that my code on an Intel MacOS  runs kind of slow even in release mode with a code that only clears the screen. I then tested and measure the time with some examples, like `cube` or `hello-triangle` and it's all the same. I also tested it on another Intel MacOS (to discard my mac's GPU being in a bad state) and the same. 

These are more or less the results I got no matter the code I run (mine or examples):
Intel MacOS: Avg FPS ~200 (more or less 120-215)
Linux x11: Avg FPS ~4000
Window 10: Avg FPS ~3500

I checked the logs, it's using Metal (it has an error about getting a GL lib and then selecting metal). The PresentMode is AutoNoVsync, and the PowerPreference is HighPerformance.

 If I try a similar example but using [notan](https://github.com/Nazariglez/notan) which uses glow (with some overhead) I got an Avg FPS of ~3700 on the same machine. 

I may be able to test this on an ARM Mac soon, I'll update the issue if that's the case. 

EDIT: I think this may be obvious but I will add it anyway just to discard that's not the initialization of the resources. If I left all the code the same, but comment the line `frame.present()` then it gets full speed.

Thanks

**Comment by Nazariglez** [comment]
Adding more context here, using metal-rs, with `cargo run --example window --release` adding `layer.set_display_sync_enabled(false);` I get ~500-650 fps, still far from the number in other platforms but it seems to be quite an improvement from wgpu's numbers.

**Comment by baznzab** [comment]
On my laptop after enabling "vulkan-portability" feature fps count jumps from 300 at max (metal&release) to 1300 (vulkan&release) running full-screen. Unfortunately wgpu doesn't allow enabling vulkan static linking, which makes it hard to exploit. It it easy to change though with official wgpu support. It's just a matter of using Entry::linked instead of Entry::load inside ash implementation and adding optional cargo feature to switch between those. Might be a good temporary solution while metal implementation is not refined.

**Comment by Wumpf** [comment]
I'm inclined to close this ticket. It's hardly actionable and for the most part compares different machines. The comment on vulkan portability being a lot faster is interesting though and might hint at something unexpected going on in our hal layer. Even if this is as it should be it would be still good to know what's going on

I generally find fps numbers are highly misleading due to the 1/time nature: 300->1300 fps is 3.3ms -> 0.8ms

Everything here talks about a single triangle, so it's not a practical usecase. Also it's not know if these are stalls that are introduced by some api calls during which other work my occur or actually "unnecessary busy works"

**Comment by baznzab** [comment]
You right, triangle test isn’t the best test of performance. For example I was able to run much more complex scene using bevy(which in turn uses Wgpu (metal backend in my case)) with competitive frame rate compared to both unity and godot. But at the same time I can’t tell it was totally smooth. Unfortunately bevy refused to run on vulkan-portability so I can’t be confident about complex scenes with lots of objects.

**Comment by Nazariglez** [comment]
> I'm inclined to close this ticket

This is fine with me, and it makes sense.
