### ISSUE TITLE
can't run bevy examples on Linux with radeon 5000 series gpu due to wgpu needing the amdgpu kernel driver

### ISSUE THREAD

**Issue by SingingBush** [gfx-rs/wgpu#4045]
if I use the Gl backend I get:

```
$ WGPU_BACKENDS=Gl cargo run --example breakout
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/examples/breakout`
2023-08-13T17:22:39.260757Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-08-13T17:22:39.261624Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.1041666666666667    
2023-08-13T17:22:40.101408Z ERROR wgpu_hal::vulkan::instance: GENERAL [../src/amd/vulkan/radv_physical_device.c:2160 (0x0)]
	Device '/dev/dri/renderD128' is not using the AMDGPU kernel driver: Invalid argument (VK_ERROR_INCOMPATIBLE_DRIVER)    
2023-08-13T17:22:40.101516Z ERROR wgpu_hal::vulkan::instance: 	objects: (type: INSTANCE, hndl: 0x562b4f39b590, name: ?)    
2023-08-13T17:22:40.118683Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD CEDAR (DRM 2.50.0 / 6.4.9-200.fc38.x86_64, LLVM 16.0.6)", vendor: 65541, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
2023-08-13T17:22:40.386133Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error
```

Vulkan is the same but that's fine as this gpu predates Vulkan

```
$ lspci -k | grep -A 3 -E "(VGA|3D)"
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Park [Mobility Radeon HD 5430/5450/5470]
	Subsystem: Sony Corporation Device 9071
	Kernel driver in use: radeon
	Kernel modules: radeon, amdgpu
```

**Comment by Wumpf** [comment]
what is the validation error you're getting, seems to be cut off from the log you posted?

In general, OpenGL support is patchy at best and more on the experimental side so it's not too surprising that this GPU would fall of the support cliff, but maybe there's some adjustments that could be made to be still compatible on the GL side.

**Comment by sangelxyz** [comment]
I'm getting the same or similar error.

It's not just bevy.

my device
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Bonaire XTX [Radeon R7 260X/360] (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. AMD Radeon R7 260X
	Flags: bus master, fast devsel, latency 0, IRQ 27, NUMA node 0
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	Memory at cf800000 (64-bit, prefetchable) [size=8M]
	I/O ports at d000 [size=256]
	Memory at feb80000 (32-bit, non-prefetchable) [size=256K]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: radeon
	Kernel modules: radeon, amdgpu

Error

`[ERROR wgpu_hal::vulkan::instance] GENERAL [../src/amd/vulkan/radv_physical_device.c:2160 (0x0)]
    	Device '/dev/dri/renderD128' is not using the AMDGPU kernel driver: Invalid argument (VK_ERROR_INCOMPATIBLE_DRIVER)
[ERROR wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x560be8210640, name: ?)
[ERROR wgpu_core::device] surface configuration failed: incompatible window kind
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Invalid surface
', /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:734:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: wgpu::backend::direct::Context::handle_error_fatal
             at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:308:9
   3: <wgpu::backend::direct::Context as wgpu::context::Context>::surface_configure
             at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:734:13
   4: <T as wgpu::context::DynContext>::surface_configure
             at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/context.rs:2056:9
   5: wgpu::Surface::configure
             at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/lib.rs:4150:9
   6: comfy_wgpu::renderer::WgpuRenderer::new::{{closure}}
             at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comfy-wgpu-0.1.2/src/renderer.rs:213:9
   7: comfy::game_loop::run_comfy_main_async::{{closure}}
             at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comfy-0.1.2/src/game_loop.rs:59:58
   8: comfytest::run::{{closure}}
             at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comfy-0.1.2/src/macros.rs:16:40
   9: pollster::block_on
             at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  10: comfytest::main
             at /home/sangel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/comfy-0.1.2/src/macros.rs:25:17
  11: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

**Comment by SingingBush** [comment]
```
2023-09-27T05:13:57.202494Z ERROR wgpu_hal::vulkan::instance: GENERAL [../src/amd/vulkan/radv_physical_device.c:2160 (0x0)]
	Device '/dev/dri/renderD128' is not using the AMDGPU kernel driver: Invalid argument (VK_ERROR_INCOMPATIBLE_DRIVER)    
2023-09-27T05:13:57.202633Z ERROR wgpu_hal::vulkan::instance: 	objects: (type: INSTANCE, hndl: 0x55ecb512e540, name: ?)    
2023-09-27T05:13:57.236358Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD CEDAR (DRM 2.50.0 / 6.4.15-200.fc38.x86_64, LLVM 16.0.6)", vendor: 65541, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
2023-09-27T05:13:58.470087Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group_layout
      note: label = `mesh2d_layout`
    Binding 0 entry is invalid
    Downlevel flags DownlevelFlags(VERTEX_STORAGE) are required but not supported on the device.
```

**Comment by Wumpf** [comment]
it's been a while :smile:

>  Downlevel flags DownlevelFlags(VERTEX_STORAGE) are required but not supported on the device.

This means the example tries to use storage buffers which aren't available on the GLES backend - since wgpu's GL backend only goes up to GLES3 (which afaik doesn't support shader storage buffers generally) there's not much we can do here unless we support more modern GL versions (but then one might as well do vulkan)
If you think the specific example should be supported with the GL backend, you need to bring this up with Bevy folks.
