### ISSUE TITLE
Depth target gets cleared before compute pass when previously used as attachement without storing values

### ISSUE THREAD

**Issue by AnotherNathan** [gfx-rs/wgpu#4146]
**Description**
Occurs with the following sequence

* render pass that clears targets and stores depth values
* render pass that does not clear targets and does not store depth values
* (wgpu clears depth target internally)
* depth target gets used as texture_depth_2d in compute pass (and has now all 0 values) -> I would have expected to still have the depth values from the first render pass available here

**Repro steps**
see the attached example

**Expected vs observed behavior**
I would expect that the depth target does not get cleared when running the compute pass.

**Extra materials**
The attached zip contains a minimal example of the issue.

**Platform**
Windows 10
wgpu 0.17 and master on Vulkan backend
RX 570 driver version 21.50.21.11

[wgpu-depth-clear-bug.zip](https://github.com/gfx-rs/wgpu/files/12640986/wgpu-depth-clear-bug.zip)

**Comment by Wumpf** [comment]
Thank you so much for the nice repro sample!

The issue here is a (I think re-occuring) miss-understanding with the store bool flag: If it's false then the content of the buffer may be discarded. This means that after any store false operation, the texture is in an undetermined state, thus forcing wgpu-core to clear it out the next time a read operation on it occurs.

Imho this is super unclear from the API as-is. I think wgpu should expose the wgpu-core `Store-Op` as is instead of putting a boolean there:
```rust
pub enum StoreOp {
    /// Discards the content of the render target.
    ///
    /// If you don't care about the contents of the target, this can be faster.
    Discard = 0,
    /// Store the result of the renderpass.
    Store = 1,
}
```

See also https://www.w3.org/TR/webgpu/#load-and-store-ops
