### ISSUE TITLE
Readme Lacks Documentation on Examples on Wasm

### ISSUE THREAD

**Issue by fr-an-k** [gfx-rs/wgpu#4169]
I would really want to use this in a commercial project, but I need cross-platform support, i.e. web + mobile + desktop (and ideally WebGL fallback). I guess it's just not there yet?

Currently the examples don't run on WASM or Android, while the wgpu homepage mentions the library supports those targets.
- wgpu-winit-android-example runs on Android, but the examples in the wgpu repository are not yet compatible with cargo apk.
- gfx-rs has a page with instructions for WASM (https://gfx-rs.github.io/2020/04/21/wgpu-web.html), which should be in the wgpu "getting started" documentation, but in Chrome 117.0.5938.89 I still get this issue: https://github.com/gfx-rs/wgpu/issues/3430 and I had to raise the rustc version in the rust-toolchain file in order to compile.

Also the WebGL backend is in the code but not mentioned on the homepage; is it not functional?

**Comment by cwfitzgerald** [comment]
> Currently the examples don't run on WASM or Android

The examples do run on wasm with both WebGPU and WebGL! You can see them online at https://wgpu.rs/examples-gl/?example=hello-triangle. You can run them yourself by `cargo xtask run-wasm --bin cube` and sub in the appropriate example. We should clear this up in the readme. 

We don't support android in the examples just due to the amount of boilerplate needed to support it. We might be able to figure out some scheme to make it work. We need to make sure the examples are still readable.

> Also the WebGL backend is in the code but not mentioned on the homepage; is it not functional?

The GL and WebGL backend are the same and work pretty well. My company (as well as a few others) use it in production.

**Comment by cwfitzgerald** [comment]
We now have documentation
