### ISSUE TITLE
`Surface::configure` can panic with "map callback was leaked"

### ISSUE THREAD

**Issue by DJMcNab** [gfx-rs/wgpu#4214]
**Description**
When `Surface::configure` is called, it's possible for the panic at:
https://github.com/gfx-rs/wgpu/blob/c85cbea39ef9133f52625b473bfffcced6b44a1e/wgpu-core/src/resource.rs#L204-L210
to trigger, specifically when:
https://github.com/gfx-rs/wgpu/blob/c85cbea39ef9133f52625b473bfffcced6b44a1e/wgpu-core/src/device/global.rs#L2343-L2345
returned a non-empty `Ok`

**Repro steps**
Running [vello](https://github.com/linebender/vello)'s examples (since https://github.com/linebender/vello/pull/350, at the time of writing https://github.com/linebender/vello/commit/34483eb787c5e3d43a940ac999b0ba98653f6a0e).
Pressing `v` to toggle vsync (and force a reconfigure) may also be required, although sometimes for reasons unknown this isn't needed

**Expected vs observed behavior**
I expected for a panic not to occur

I observed that a panic occured

**Platform**
Wayland Gnome on Fedora 38 on an intel i5-1240p
Reproduction also confirmed on ["on Sway and with an amdgpu"](https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/Map.20Callbacks.20Leak/near/395311371)

**Comment by benjamin-sieffert** [comment]
Running into the same issue after upgrading wgpu-core from 0.17.0 to 0.17.1.
Since supposedly it is related to VSync, here is what happens for me, using amdgpu kernel driver on linux, no `amdvlk` installed, i.e. vulkan via mesa is used (as far as I understand all this).
`Automatically choosing presentation mode by rule AutoNoVsync. Chose Immediate`
My monitor can do FreeSync, though. Maybe first `Immediate` is used, but then immediately switched to Adaptive-Sync?

**Comment by dhardy** [comment]
#4220 does not fix this for me: I still get "Map callback was leaked" when resizing a window using 152c23903123b74db49153e332e896c0b8f9bc8c.

Reproduce:
```
git clone https://github.com/kas-gui/kas.git --single-branch --branch wgpu
cd kas
cargo run --example layout
# resize the window
```

**Comment by DJMcNab** [comment]
It looks to me like the callbacks are only called if there's an error

Not checked the code on a big screen though

**Comment by nical** [comment]
Gosh, you are right, that fix wasn't very good.
