### ISSUE TITLE
Frontend for HLSL

### ISSUE THREAD

**Issue by BrandonDyer64** [gfx-rs/wgpu#4305]
(Discussion) Would it be reasonable to include a frontend for HLSL as part of the scope of naga? It’s a fairly popular standard for shading with thousands of existing scripts.

I think it would be very useful for a variety of different applications to have the ability to put HLSL source through naga.

Note that this issue isn’t for tracking the progress of implementation, but rather for including HLSL as part of the scope of the library.

**Comment by cwfitzgerald** [comment]
I'm going to close this as out of scope. HLSL is a very complex language whose definition is basically "what dxc accepts" and I don't think the development of an hlsl frontend would be a good use of developer time.

If someone feels strongly otherwise they can prototype in an out-of-tree frontend for Naga.
