### ISSUE TITLE
Support override-expression for `workgroup_size`

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#4450]
Required for https://gpuharbor.ucsc.edu/

```
Shader '' parsing error: expected signed integer literal of 32-bit width, found 'workgroupXSize'
    ┌─ wgsl:111:34
    │
111 │ [[stage(compute), workgroup_size(workgroupXSize)]] fn main(
    │                                  ^^^^^^^^^^^^^^ expected signed integer literal of 32-bit width

, caused by: expected signed integer literal of 32-bit width, found 'workgroupXSize'
```

**Comment by kentslaney** [comment]
[This is the relevant line for specifying `workgroup_size` now](https://github.com/gfx-rs/wgpu/blob/1a643291c2e8854ba7e4f5445a4388202731bfa1/naga/src/front/wgsl/parse/mod.rs#L2463) (also see: [[1]](https://github.com/gfx-rs/wgpu/blob/1a643291c2e8854ba7e4f5445a4388202731bfa1/naga/src/back/pipeline_constants.rs#L190) [[2]](https://github.com/gfx-rs/wgpu/blob/1ea5498038b2fd0392bd6cbd81ec71b2438e5c95/naga/src/front/wgsl/lower/mod.rs#L1327) [[3]](https://github.com/gfx-rs/wgpu/blob/trunk/naga/src/proc/constant_evaluator.rs#L843))

It looks like expressions support overrides, it's just that they don't get compiled to const expressions in [1] since `Module` requires `ast::EntryPoint` to resolve into `u32`s for `crate::EntryPoint.workgroup_size`  by then.

Maybe we can add a `workgroup_size_overrides: Option<[Option<Handle<Expression>>; 3]>` attribute to `crate::EntryPoint` that gets evaluated in [1] and initialize the `u32`s to zeros in [2] if `size_expr` is an `ExpressionKind::Override`.

I'll give it a try sometime this week.
