### ISSUE TITLE
Commit #4657 appears to introduce a race condition

### ISSUE THREAD

**Issue by apessino** [gfx-rs/wgpu#4668]
Since syncing yesterday, I started getting consistent panics here:

```
thread 'main' panicked at D:\projects\rust\wgpu\wgpu-core\src\track\buffer.rs:324:17:
Tried to insert buffer already tracked
```

in my code where I shut down wgpu buffers and immediately create new ones. I tracked it down to commit [#4657](https://github.com/gfx-rs/wgpu/pull/4657).

Looking at the changes, my best guess is that calls to `take_and_mark_destroyed` such as this one in `D:\projects\rust\wgpu\wgpu-core\src\device\global.rs`:

```
            //TODO: lock pending writes separately, keep the device read-only
            let (mut device_guard, mut token) = hub.devices.write(&mut token);

            log::trace!("Buffer::destroy {buffer_id:?}");
            let (mut buffer_guard, _) = hub.buffers.write(&mut token);
            let mut buffer = buffer_guard
                .take_and_mark_destroyed(buffer_id)
                .map_err(|_| resource::DestroyError::Invalid)?;

            let device = &mut device_guard[buffer.device_id.value];
```

are allowing ids to be reused before the corresponding async GPU resources are released. This seems to be validated by the fact that I can make the panic disappear by waiting at a breakpoint before the id is reused.

I am reverting to before this commit until the problem can be properly diagnosed by someone "in the know" - please let me know if I can provide any further help!

Thanks!

**Comment by ErichDonGubler** [comment]
@nical ☝🏻

**Comment by nical** [comment]
I found a way to reproduce this. The problem is that destroying the buffer enqueues it for some later processing during device polling and during that time the buffer ID is tracked. With the change I made, the buffer ID may be unregistered as soon as we drop it just like in the case where the buffer was created in an invalid state). That should be fine except that the tracking stuff expects the ID to be unregistered later.

I think that the easiest way to deal with this is to add a `Element::Destroyed(T)` enum variant in the storage and treat the destroyed case separately from the created-invalid case. This way `storage.get_mut(id)` will still return an error, but we can keep the previous behavior for unregistering ids after when `destroy` and `drop` happen before polling.
