### ISSUE TITLE
Possible inconsistency with IDL spec in BufferUsage flag

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu#467]
In wgpu-py we parse `wgpu.py` and the IDL spec to be able to automate some parts of our API and see where we need extra logic to tie things together. This parser/codegen script also compares flags and enums and generates a [little report](https://github.com/almarklein/wgpu-py/blob/master/wgpu/resources/codegen_report.md).

I saw that the `INDIRECT` field of the `BufferUsage` flag is `256` in IDL and `512` in `wgpu.h`. I was wondering whether this is considered a bug or not. Should I report inconsistencies like this, or deal with them in our lib?

**Comment by kvark** [comment]
Thank you for the report!
This is kind of intentional. We didn't want to disrupt `INDIRECT` specifically, but we did want to add `STORAGE_READ` besides the `STORAGE`, and the spec is about to get those read-only states as well, see https://github.com/gpuweb/gpuweb/issues/541

So, I think we can address this by switching `INDIRECT` back to 256 and assigning `STORAGE_READ` to 256, at least for now. Want to make a small PR?
