### ISSUE TITLE
Rename feature `serde` to `serde1`

### ISSUE THREAD

**Issue by daxpedda** [gfx-rs/wgpu#476]
While implementing #475 is realized that we are not activating `serde` on `gfx-hal` when `serde` is used on `wgpu-native/core`.
I don't know of any way to do this without renaming the feature, unless we use a `serde` shim crate.

**Comment by kvark** [comment]
IIRC, this was intentional. Serde feature here means that the types from *this* crate get serialize implementations. If you need types from `gfx-hal` to *also* serialize, you can technically add it to your dependency list.

To clarify, serializing wgpu-core types does *not* require gfx-hal types to be serializable.

**Comment by kvark** [comment]
Also, wgpu-core doesn't re-export gfx-hal, so if you want to rely on serialization of any gfx-hal types, you are depending on that crate from your application, and therefore it's not a problem for you to enable "serde" feature from your manifest.
Saying that, I think the issue can be closed. Please reach back if I'm getting this wrong!

**Comment by daxpedda** [comment]
I was writing a response when you posted this: https://github.com/gfx-rs/wgpu/pull/475#pullrequestreview-348406029.

Guess that resolves the issue.
