### ISSUE TITLE
Validation Error when drawing sliced index buffer - Index X extends beyond limit Y

### ISSUE THREAD

**Issue by willdady** [gfx-rs/wgpu#5334]
I'm having an issue when attempting to do an indexed draw with a sliced index buffer.

I'm simply trying to render two 2D quads (8 vertices, 12 indices).

Both quads render fine with the following code:

```rust
render_pass.set_index_buffer(
  self.particle_index_buffer.slice(0..12), // .slice(..) also works
  wgpu::IndexFormat::Uint16,
);
render_pass.draw_indexed(0..12, 0, 0..1);
```

However, when attempting to render just the second quad by adjusting the index range inside `draw_render` the app panics.

```rust
render_pass.set_index_buffer(
  self.particle_index_buffer.slice(0..12), 
  wgpu::IndexFormat::Uint16,
);
render_pass.draw_indexed(6..12, 0, 0..1);
```

```
Validation Error

Caused by:
    In a RenderPass
      note: encoder = `Render Encoder`
    In a draw command, indexed:true indirect:false
      note: render pipeline = `Particle Render Pipeline`
    Index 12 extends beyond limit 6. Did you bind the correct index buffer?
```

I don't undersand this error. The range in the draw call, `6..12` in still within the index buffer slice range, `0..12`? 

Why is the limit **6** as mentioned in the error message? Where is that coming from?

Similarly, I would have thought I could just render the second quad by doing the following...
```rust
render_pass.set_index_buffer(
    self.particle_index_buffer.slice(6..12),
    wgpu::IndexFormat::Uint16,
);
render_pass.draw_indexed(0..6, 0, 0..1);
```

```
Validation Error

Caused by:
    In a RenderPass
      note: encoder = `Render Encoder`
    In a draw command, indexed:true indirect:false
      note: render pipeline = `Particle Render Pipeline`
    Index 6 extends beyond limit 3. Did you bind the correct index buffer?
```

What am I missing?

**Platform**
* MacOS
* wgpu v0.19.3

**Comment by Wumpf** [comment]
I'm a bit unclear why
```
render_pass.set_index_buffer(
  self.particle_index_buffer.slice(0..12), // .slice(..) also works
  wgpu::IndexFormat::Uint16,
);
render_pass.draw_indexed(0..12, 0, 0..1);
```
would work. Can you confirm that?

`self.particle_index_buffer.slice(0..12),` Means that you're binding the **byte range** 0-12, i.e. you're binding 6 indices (since with `wgpu::IndexFormat::Uint16` each index takes two bytes), therefore both `render_pass.draw_indexed(0..12, 0, 0..1);` and `render_pass.draw_indexed(6..12, 0, 0..1);` should fail with 

```
Caused by:
    In a RenderPass
      note: encoder = `Render Encoder`
    In a draw command, indexed:true indirect:false
      note: render pipeline = `Particle Render Pipeline`
    Index 12 extends beyond limit 6. Did you bind the correct index buffer?
```
-> there's a range of indices ending at 12, which is beyond the limit of 6 indices.


Same story on the second case: You're binding 3 indices (bytes 6-12 -> indices 3-6, therefore 3 indices)

**Comment by willdady** [comment]
You are right. I had reached a similar conclusion shortly after my original
post. I have to double the values used in the index buffer slice as each item is 2 bytes, not 1.

This will render just the second quad fine ✅

```rust
render_pass.set_index_buffer(
    self.particle_index_buffer.slice(12..24),
    wgpu::IndexFormat::Uint16,
);
render_pass.draw_indexed(0..6, 0, 0..1);
```

Now I'm confused by something else 🙂

I'm confused about when `Buffer::slice` expects a byte range and when it doesn't.

This code renders both quads successfully...

```rust
render_pass.set_pipeline(&self.particle_render_pipeline);
render_pass.set_vertex_buffer(0, self.particle_vertex_buffer.slice(0..8)); // <- Not a byte range like index buffer slice?
render_pass.set_index_buffer(
    self.particle_index_buffer.slice(0..24),
    wgpu::IndexFormat::Uint16,
);
render_pass.draw_indexed(0..12, 0, 0..1);
```

Note how I slice the vertex buffer compared to the index buffer.
Why can I slice the vertex buffer based on **number of vertices** without having to consider the byte size of each item (vertex) like I have to when slicing the index buffer?

I have confirmed the size of each vertex is **28 bytes**.

```rust
println!("Particle bytes: {}", std::mem::size_of::<ParticleVertex>()); // 28
```

Why don't I also have to multiply the vertex buffer slice range by the **byte size** of each vertex? e.g. `self.particle_vertex_buffer.slice(0..8*28)`

**Comment by Wumpf** [comment]
> I'm confused about when Buffer::slice expects a byte range and when it doesn't.

Slice is always in bytes because the buffer has no way of knowing how its data is about to be interpreted.

The problem you're facing is that we're currently not validating vertex buffer accesses correctly on all platforms, see:
* #2432 

It's a fairly complicated problem since it requires knowing the contents of the index buffer which isn't always easy. Wgpu is missing this right now and it's required for webgpu compliance. For non-indexed draw calls we already do the full (trivial) validation on whether the vertex buffer range makes sense.

Closing the issue since the original problem is resolved and the follow-up is a known issue.
