### ISSUE TITLE
a problem, i don't know what caused it.

### ISSUE THREAD

**Issue by aqdd** [gfx-rs/wgpu#5360]
https://github.com/DioxusLabs/dioxus/issues/2012#issue-2172960785

**Comment by Wumpf** [comment]
@aqdd please be more mindful in the future when filing bugs, the title is not helpful/actionable at all. The description on the linked issue is not much better either.
High cpu usage during resize can be caused by all sort of things, without a trace what causes this there's no reason to believe this is a wgpu issue. Generally, resizing is a costly operation, so it's not too surprising either.

**Comment by aqdd** [comment]
@Wumpf my bad, just i found it, when i resize window again and again, Tencent PC Manager cpu usage up to 80%+, and i tried other desktop app, such as vscode, cpu usage is very normal. 
just like this issue title, i don't know what caused it. so i posted this issue. 

If this problem is not caused by wgpu, that's fine.
