### ISSUE TITLE
texture_2d_array error

### ISSUE THREAD

**Issue by Alphapage** [gfx-rs/wgpu#5467]
Hello,

**Description**
I am trying to use texture_2d_array, but without success: I always get 
`
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension Y is zero
`

**Repro steps**
I tried to set depth_or_array_layers to 6 or 1 and count too.

**Expected vs observed behavior**
There are no example on how to use `texture_2d_array`, so maybe I am missing something but this error doesn't tell me more.

**Platform**
Macosx, wgpu 0.19.3

Thank you in advance for your help.

**Comment by teoxoy** [comment]
The error says that the `y` dimension is 0 not `depth_or_array_layers`.

**Comment by Alphapage** [comment]
Maybe you can help me more:
- texture format must be the same for all texture_2d in the array
- width and height must be the same for all texture_2d in the array
So, texture_2d_array inherits texture format and width and height from the first texture 2D.
Is it true ?

**Comment by teoxoy** [comment]
The first 2 bullet points are correct.

> So, texture_2d_array inherits texture format and width and height from the first texture 2D.

I would say it's the opposite but it doesn't really matter.

The way I would think about it is that the `texture_2d_array` is a container of 2D textures and the format/width/height are all metadata for those textures but they are present on the container itself since they are the same for all the textures inside of it.
