### ISSUE TITLE
Strongly typed buffers with bytemuck::Pod

### ISSUE THREAD

**Issue by axelkar** [gfx-rs/wgpu#5470]
**Is your feature request related to a problem? Please describe.**
I don't like how I have to use `bytemuck::cast` or equivalent when initializing, writing or reading to buffers containing "host-shareable types".

**Describe the solution you'd like**
Add a generic argument to `wgpu::Buffer` with `T: bytemuck::Pod` and `PhantomData<T>` but leave the possibility of using your own bytes (maybe a new type?).

This adds a new dependency so it should probably be feature-gated.

**Alternatives**

Use encase for runtime encoding:

- https://github.com/ScanMountGoat/wgsl_to_wgpu
- https://lib.rs/crates/encase
- https://github.com/bevyengine/bevy/blob/main/crates/bevy_encase_derive/src/lib.rs
- https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/globals.rs#L47

**Additional context**

The unmaintained `ewgpu` implements it:

- https://github.com/DoeringChristian/ewgpu/blob/main/src/buffer.rs
- https://docs.rs/ewgpu/0.1.0/ewgpu/buffer/struct.Buffer.html

**Comment by lylythechosenone** [comment]
I don't think this is something we should pursue. I like the idea, but I think it's slightly misguided. A `Buffer` is not necessarily typed at all, it is simply a blob of memory. Certain types of buffers may be typed, but I don't want to restrict buffers to arrays of a single type. I also think something like this would be drifting away from the WebGPU spec.

I fully support a crate like ewgpu doing this. I'm quite sad that it's now unmaintained, because it seems useful.

**Comment by kpreid** [comment]
> I don't want to restrict buffers to arrays of a single type.

While I don't specifically want to see this done, note that there is no added restriction as long as one of the possible types for a buffer is `[u8]`.

**Comment by Wumpf** [comment]
closed as 'not planned' as per previous explanations given. There's plenty of runtime encoding libraries and even more (maintained) alternatives in this space may still be good to have around welcome but they should live outside of wgpu.
