### ISSUE TITLE
The maximum vertex buffer input bindings is set too low

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu#558]
https://github.com/gfx-rs/wgpu/blob/77d95f5ecdce6a78f1803c4644fd4a245a7d9757/wgpu-core/src/device/mod.rs#L37

A super conservative value would be 16, but modern hardware supports 32 vertex input bindings.

https://vulkan.gpuinfo.org/displaydevicelimit.php?name=maxVertexInputBindings

The error I ran into manifested as a slice index out of bounds. I think this should really be a `SmallVec` or something similar that can handle more than the bare minimum. 

https://github.com/gfx-rs/wgpu/blob/77d95f5ecdce6a78f1803c4644fd4a245a7d9757/wgpu-core/src/command/render.rs#L971

**Comment by kvark** [comment]
Thank you for filing!

>A super conservative value would be 16, but modern hardware supports 32 vertex input bindings.

What use case do you have to need more than 4? :)

You are right that we need to support at least 16, according to Vulkan capabilities and our code in gfx-rs for other backends. Although, it's a bit more tricky than it seems on Metal: the vertex bindings are shared between descriptor resources and vertex attributes. And it can have up to 31 vertex buffer in total... So there must be a balance between how many vertex buffers we allow coming for the attributes, versus ones coming in a bind group. And I'd much prefer to have the higher limit for the latter, since I don't find multiple vertex buffers particularly useful.

> The error I ran into manifested as a slice index out of bounds. I think this should really be a SmallVec or something similar that can handle more than the bare minimum.

Yes, I think `SmallVec` is a proper primitive in general for anything limit-related, since we know the baseline (minimum requirements), we can specify it as a fixed portion. In the near future, the limit on the vertex buffer count will be exposed in `Limits`, and you'll be able to request more than the standard amount.

**Comment by aloucks** [comment]
> What use case do you have to need more than 4? :)

Loading glTF files using their buffers as-is without converting the vertex input.

The attributes aren't necessarily interleaved and the offset into the view sometimes exceeds the stride. It makes it difficult or impossible to put the attributes on a single buffer binding and you either need to (1) create an input binding per attribute or (2) pre-process the input into a custom/known vertex format. I'm trying to solve for (1) because (2) prevents you from loading the data directly.

Although most assets aren't going to have *all* of these attributes, once you run into models with animation, you can go past the limit of 8 pretty easily (which is what happened to me).

0. Position
1. Normal
1. Tangent
1. UV1
1. UV2
1. Color
1. Joint1
1. Weight1
1. Joint2
1. Weight2
1. MorphTarget0_Position
1. MorphTarget0_Normal
1. MorphTarget0_Tangent
1. MorphTarget1_Position
1. MorphTarget1_Normal
1. MorphTarget1_Tangent
1. MorphTarget2_Position **
1. MorphTarget2_Normal
1. MorphTarget2_Tangent
1. MorphTarget3_Position
1. MorphTarget3_Normal
1. MorphTarget3_Tangent

** I have a flag in the shader that disables morph targets 2 and 3 during compilation if only 16 input bindings are supported. This is why I opened https://github.com/gfx-rs/wgpu-rs/issues/239.
