### ISSUE TITLE
Weird behaviour on transparent materials

### ISSUE THREAD

**Issue by Khalzz** [gfx-rs/wgpu#5892]
**Description**
Im working on a game engine using wgpu, the problem is that in it im adding .gltf objects with transparent materials, when i do the materials looks correct sometimes, letting the image behind pass through so you can see what is behind the "transparent object" but sometimes in random moments when i start the project some of the objects that should be "seen trough the transparent object" are not rendered, while others do, sometimes all are rendered, others just some, and sometimes none.

Example: In each of this examples the only thing i did to change the output was just closing the game and opening it again.

https://github.com/gfx-rs/wgpu/assets/63627567/5d5c28eb-4061-4923-b45f-7f05376b4eca
https://github.com/gfx-rs/wgpu/assets/63627567/ee0ea2f5-e6d2-4c2c-8667-521032324188
https://github.com/gfx-rs/wgpu/assets/63627567/8f183874-0ba2-4ea1-afaa-de045c4fb330

**Repro steps**
Here is the repo with the bug https://github.com/Khalzz/Project-Skies and to reproduce it just open the game and the cabin of the plane (wich haves transparent elements) will sometimes see through the plane, or se through other objects in the world

**Platform**
OS: Windows 11
WGPU: 0.18.0

**Comment by Wumpf** [comment]
It looks like you kept z writing enabled!

When rendering transparent objects, you want to disable writing to the z buffer and (!) render them last. If you keep z buffer writes enabled, your transparent object can cause objects behind it to be hidden if they're rendered after the transparent geometry. Once disabled, it becomes obvious that you have to have everything in place ahead of time, otherwise they get hidden by anything that draws later. Also, by rendering them last you make sure that the color you want to blend with is in the backbuffer in the first place.

With this in place you'll sooner or later will notice that this means that within your transparent objects you have to order from far to near, because the z buffer can't help you with ordering here since the color of closer objects depends on all objects that are further away. Also, for any closed surface (anything that isn't just a double sided triangle), you have to render first the backfacing and then the front facing triangles for the same reason

All this in turn breaks down once sorting on a per draw call basis isn't enough, either because a single draw call stacks more than one front+back facing triangle or due to transparent triangles intersecting. There's various more sophisticated algorithms to tackle this under they keyword "order independent transparency"

Even mildly complex transparency is a bit of a headache for this and other reasons (e.g. various screen space effects or screen space based shading approaches) and therefore many game engines try avoiding or working around it.
