### ISSUE TITLE
Metal backend uses of `MTLCommandEncoder` and `MTLCommandBuffer` inefficiently in internal backends

### ISSUE THREAD

**Issue by Snowapril** [gfx-rs/wgpu#6001]
Hello.

I have a question while trying to run water sample with wgpu metal backend.
When I captured water sample with Xcode gpu capture, there are many `MTLCommandBuffers` and `MTLCommandEncoders` as shown below picture.
![image](https://github.com/user-attachments/assets/b2d6bb27-15a1-4279-8317-9e4c1a7d4bd9)

It seems that one `MTLCommandEncoder` requires one `MTLCommandBuffer` to be opened and closed immediately, while three `MTLCommandEncoders` could have shared just one `MTLCommandBuffer`.
Furthermore, since Terrain Render Pipeline and Water Render Pipeline have the same framebuffer formats, it would be more efficient to share the same `MTLRenderCommandEncoder`.

Could I ask that why the uses of MTLCommandBuffer/MTLCommandEncoder are somewhat inefficient? 

Thank you.

**Comment by Wumpf** [comment]
This is pretty well explained in the ticket about the general problem here:
* https://github.com/gfx-rs/wgpu/issues/5738

in a nutshell: Other APIs require various barrier transitions which force wgpu to do some command buffer splitting. However, most of this isn't needed on Metal and right now wgpu-core isn't aware of this because wgpu-hal isn't communicating this kind of "backend property" to where all the command buffer creation happens.

It's fair to say this is a known performance bug

**Comment by Snowapril** [comment]
Thank you. I forgot duplicate issue searching 😂

**Comment by Wumpf** [comment]
no worries, it had a surprisingly hard time finding it again as well!
