### ISSUE TITLE
Use strongly typed Ids

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#61]
With `#[repr(transparent)]` we should be able to wrap our `Id` new newtypes to avoid accidental collisions. This is important for aliased indices especially: `QueueId` vs `DeviceId`, `CommandEncoderId` vs `CommandBufferId`.

**Comment by psincf** [comment]
When `Id` newtypes are created, some functions don't work, because they are expecting a `hub::Id` instead of `NewtypeId`.
In that case, we can do : 

- `struct NewtypeId(hub::Id)`         => `new_type_id.0`
- `struct NewtypeId(hub::Id)`         => `let Newtypeid(id) = new_type_id`
- `struct NewtypeId(id: hub::Id)`    =>  `new_type_id.id`

Is there a preferred syntax?

**Comment by vitvakatu** [comment]
IMO, the prefered way is to define `From` trait

**Comment by psincf** [comment]
Here is an example with the `From` trait with InstanceId : #https://github.com/psincf/wgpu/commit/8a3145a93f7dd6c2597e375981bc56fd0d0d3247.
It would need a different `Id_from!` macro for `QueueId`, `CommandEncoderId` and `SwapChainId`

**Comment by kvark** [comment]
@psincf 
> When Id newtypes are created, some functions don't work, because they are expecting a hub::Id instead of NewtypeId.

On the implementation side, seeing "id.0" is fairly unambiguous, so that would be my preference. I don't think we should be defining `From` for those as that level of indirection doesn't provide much benefit. I.e. seeing `id.into()` is much more ambiguous than a simple `id.0`.

**Comment by psincf** [comment]
> On the implementation side, seeing "id.0" is fairly unambiguous, so that would be my preference. I don't think we should be defining `From` for those as that level of indirection doesn't provide much benefit. I.e. seeing `id.into()` is much more ambiguous than a simple `id.0`.


We can also `impl` `as_raw()` like in Ash for example : [link](https://github.com/MaikKlein/ash/blob/master/ash/src/extensions/experimental/amd.rs#L58-L68). It's clear while still being thin.
I don't have a clear preference between all these possibilities, but if a solution is prefered, I can make a PR.

**Comment by kvark** [comment]
That would also be fine by me. The implementator gets to pick :)

**Comment by psincf** [comment]
@kvark 

I tried to make a "strong typed" branch with the `id.0` pattern, but it can be changed if needed ;).
I ran into some issue while doing this, and I am not sure how to deal with them : 
1. with `QueueId`, `CommandEncoderId `and `SwapChainId`, I had to do -> `(id.0).0`. Maybe that is not very aesthetic?
2. In order to work with the implemented function of `Tracker` like `query()`, I implemented `NewId` to some new types (It would be better to implement it for all)
3. For the other functions of Tracker: `get_with_extended_usage()` and `get_with_replaced_usage()` I had to create a `ToId` trait, because these `fn` are expected `Hub::Id` normally. [link](https://github.com/psincf/wgpu/blob/strong/wgpu-native/src/track.rs#L277). Also this trait can be used to replace all the `id.0` and maybe fix the issue 1?
4. `device_track_view()` has a `BufferId` parameter, but seems to work with a `TextureViewId` so I changed it
5. In wgpu-rs, `copy_buffer_to_buffer`, `copy_buffer_to_texture`, `copy_texture_to_buffer`and `copy_texture_to_texture` are working with a `CommandEncoderId`, but the underlying function of wgpu-native are waiting a `CommandBufferId` as parameter

Here is the [branch](https://github.com/psincf/wgpu/tree/strong), it is still a draft, and need to be cleaned, particularly in the lib.rs of wgpu-native, where types are declared.
I didn't make a PR, because I felt that it wasn't "neat".
Also, I don't understand all of the library at the moment, so I didn't know what to do sometimes. If someone want to add some changes or maybe make a PR, feel free to clone this branch and work from it if you want.

**Comment by kvark** [comment]
@psincf thank you for taking a stab at it!

Part of your confusion comes from the fact that some ID types collide in wgpu:
  - command buffer and command encoder are represented by the same thing
  - device and queue are the same thing
  - surface and swapchain are the same thing

For changes where you aren't sure about being right, Github recently added a "draft PR" function. It is preferred for discussion since we can comment in-code. Please make a draft PR and we'll go from there?

**Comment by psincf** [comment]
draft PR : https://github.com/gfx-rs/wgpu/pull/136
