### ISSUE TITLE
New minor release?

### ISSUE THREAD

**Issue by bircni** [gfx-rs/wgpu#6240]
As @emilk is aiming to do a new major egui release in the next 2 weeks, we would like to use the newer wgpu version for egui.
https://github.com/emilk/egui/pull/4980#issuecomment-2333392984
I order to support the newer version egui needs wgpu to use glow `0.14`.
This is already on the main branch.

When will be the next release?

FYI:
https://github.com/emilk/egui/pull/4952

**Comment by Wumpf** [comment]
wgpu releases roughly every 12 weeks, the next release is scheduled on 9th October
https://github.com/gfx-rs/wgpu/milestones

I don't quite understand how egui's glow backend is depending on the glow update on wgpu? This just means that the glow library uses in eframe without wgpu would be a different than the one in eframe with wgpu. Don't even think you can enable both glow and wgpu backend at the same time in eframe.
Yes, this will make cargo deny unhappy, but it's not an _actual_ issue since afaik the build combination of having both wgpu & glow enabled on eframe is not valid.
