### ISSUE TITLE
WGLSL and WebGL Primary Full Support

### ISSUE THREAD

**Issue by KooIaIa** [gfx-rs/wgpu#6246]
Currently both WGSL and GLSL are both marked as Secondary Supported platforms. 🆗

Is the goal for WebGPU and WebGL to eventually be both front-end and back-end Primary supported platforms?  ✅

I'm confused if WebGPU and WebGL are a goal for translating between them and SPIR-V or if the plan is to keep them as Secondary support.

Thanks and excited for graphics finally standardizing like GLTF 1.0 dreamed of!

**Comment by Wumpf** [comment]
It's close to impossible to implement WebGPU on top of WebGL due to various missing capabilities (easiest example: compute shaders are missing). If you look closely it actually says `🆗 = Downlevel/Best Effort Support`, so it's not so much secondary in the sense that it doesn't get as much support (that's kinda true due to practicalities, but not so much intentional) but rather that it simply can't support the full spec with reasonable effort.

Hope that answers it Please re-open if you have follow-up questions or try the `Discussions` feature or check our Matrix chat https://github.com/gfx-rs/wgpu?tab=readme-ov-file#community

**Comment by KooIaIa** [comment]
Is there a good example of compute shaders that can and cannot be done in WebGL2 by mapping compute operations to its graphics primitives?

In WebGPU it prefers memory to be in 32bit chunks and forces you to pad out variables. This is similar to storing generic compute variables in a 32bit texture isn't it?

**Comment by Wumpf** [comment]
With enough effort and performance sacrifices you get _most_ things done without. Compute shader is a different paradigm so some operations are just awful or incredibly inefficient to write as graphics primitives. Generally where it starts to break down completely is scatter operations which would need to be awkwardly emulated with a vertex shader. Also any form of structured data read/write that can't be easily formulated as an image operation. Then there's lack of barriers, lack of flexible dispatch sizes, no atomics,... the list goes on. All of which are associated with compute shader support

**Comment by KooIaIa** [comment]
Couldn't it make sense then to break the support into two categories: graphics and compute?

Is it possible to draw the line between the two? WebGL not getting compute shaders ported from SPIR-V / WebGPU wouldn't suprise anyone.

**Comment by Wumpf** [comment]
> Couldn't it make sense then to break the support into two categories: graphics and compute?

No. ;)


Refer to the comments on [`DownlevelFlags`](https://docs.rs/wgpu/latest/wgpu/struct.DownlevelFlags.html) and the [default webgl downlevel limits](https://docs.rs/wgpu/latest/wgpu/struct.Limits.html#method.downlevel_webgl2_defaults) for details
