### ISSUE TITLE
Get error on startup

### ISSUE THREAD

**Issue by IamRezaMousavi** [gfx-rs/wgpu#6261]
**Description**
When lapce starts, it shows a window and terminates very quickly.

**Extra materials**
![Screenshot from 2024-09-13 12-23-28](https://github.com/user-attachments/assets/0cfe0f29-47bd-4b06-8aa6-4632aafc5697)

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.

![Screenshot from 2024-09-13 12-20-35](https://github.com/user-attachments/assets/cc4f9cd2-9280-460e-b85a-3bb191d58f42)

**Comment by Wumpf** [comment]
According to the log - please do put them as a code block and not as a screenshot next time! - wgpu picked a GL adapter which while being 4.5 reports that it doesn't support any shader storage buffer objects on vertex shader (== arbitrary buffer access). That's rather strange!
You'll probably have to update your drivers and try to find out why it doesn't run with Vulkan (there bound to be more log on that that you haven't put in there)

You probably want to file this issue against lapce instead.

Closing since I don't think there's anything to do from wgpu's side. Please re-open if there's reason to believe otherwise.
