### ISSUE TITLE
BlendDescriptor, BlendFactor and BlendOperation are unavailable from wgpu.

### ISSUE THREAD

**Issue by seivan** [gfx-rs/wgpu#63]
Had to import `wgpu_native` for them. 
[This](https://github.com/gfx-rs/wgpu/pull/57) removed `wgpu_native` from the examples and the cargo file. 

What's the idea between `wgpu_native` and `wgpu` - are you supposed to refer to both when working with `wgpu` in a Rust project, or should `wgpu-rs` alone suffice?

**Comment by grovesNL** [comment]
wgpu_native contains the raw C externs (to match the [WebGPU IDL](https://github.com/gpuweb/gpuweb/blob/master/design/sketch.webidl)), while wgpu is a more Rust-friendly API that wraps that C API.

I don't think it's intentional for them to be left out, they should be added to the `pub use` section of wpgu: https://github.com/gfx-rs/wgpu/blob/master/wgpu-rs/src/lib.rs#L14

**Comment by kvark** [comment]
These structures are [now exposed](https://github.com/gfx-rs/wgpu/pull/62/files#diff-194636ad6209070b52ff6bd60a907cf3R15) as of #62
The idea behind `wgpu-rs` is that the users would only need it and nothing else.

**Comment by kvark** [comment]
@seivan note: I closed the issue because I consider it resolved. Please feel free to continue the discussion, however note that we also have a dedicated chat room to talk: https://gitter.im/gfx-rs/webgpu
