### ISSUE TITLE
Separate winit optional feature

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#64]
With #62 `winit` is now implied when building in "local" mode. We should still make it optional. That may require changes to gfx-rs first, since all of the backends (except `emtpy`) have it enabled by default.

**Comment by seivan** [comment]
Right now, Winit isn't optional even though the feature flags might give the impression it is. Winit is referenced outside of conditional code so it's a strict requirement (unless I'm mistaken). 
It would be nice to either get rid of it completely or make it really optional. 

I'd like to be create a surface with Windows hwnd or a Metal layer directly instead of depending on Winit. So far I'm using SDL, but anything should use the same functions including Winit.

**Comment by kvark** [comment]
We need to use the `gfx-backend-*` crates with no default features, explicitly enabling `winit` if our feature is on.
