### ISSUE TITLE
Shader preemption

### ISSUE THREAD

**Issue by DemiMarie** [gfx-rs/wgpu#6581]
**Is your feature request related to a problem? Please describe.**
GPU resets are often very disruptive.  For instance, on AMD GPUs, they often kill the Wayland compositor and thus bring down the entire user login session.  On macOS, GPU resets still cause glitches in other applications.

**Describe the solution you'd like**
Insert preemption polls in generated shaders to ensure that a shader terminates before the driver must kill it.  This could also allow long-running compute by saving and restoring shader state.

**Describe alternatives you've considered**
None.

**Additional context**
WGPU must ensure that shaders terminate to avoid memory unsafety in generated code.

[JimB edit] prior conversation: https://github.com/gfx-rs/wgpu/issues/6528#issuecomment-2488155684

**Comment by jimblandy** [comment]
That's an interesting idea. My guess is that it would not pan out in practice.

## Control flow uniformity questions

These early exits would need to occur in both uniform and non-uniform control flow.

Because shaders are run in SIMD batches, with one thread ('invocation', in WebGPU terms) per SIMD lane, shader languages draw a distinction between uniform control flow, where all the invocations branch together, and non-uniform control flow, where you mask off some lanes but let other lanes continue to run.

Although the branches you're suggesting we introduce would be branches on uniform conditions (that is, conditions that are the same for all SIMD lanes), if they occurred in non-uniform control flow, only those invocations that were active would be affected. In other words, not all invocations would execute the `OpTerminateInvocation`. You would need to wait until control flow had reconverged to terminate the rest of them. ("Reconvergence" is the restoration of uniform control flow after some necessarily non-uniform execution has completed.)

Unfortunately, when the Google folks were doing initial investigations for the subgroup operations proposal, they found that in practice re-convergence happened much less often than you might hope. I believe it varied from driver to driver.

A third example: Something that is well-specified, but is still surprising, is [helper invocations](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpDemoteToHelperInvocation). This means that a `discard` statement in a fragment shader doesn't actually stop execution *of that invocation*.

## WGPU is not the best place for this

Since the driver has more information, it should always be able to do a better job at this than wgpu could possibly do. So this should be the driver's job.

GPU resets are usually caused by the kernel driver, which imposes timeouts and detects GPU traps. These are not things that userspace can always reasonably anticipate.

One could implement this as Vulkan layer. There already exists a "GPU-based validation" layer that operates by tweaking the SPIR-V code that passes through it on the way to the driver. This PR's idea could be implemented in a similar way.

## This is not quite what Firefox needs to avoid UB

Firefox is only one of many users of WGPU, and simply because something is not what Firefox needs does not imply that it is not of interest to WGPU. That said:

Firefox is not actually on the hook to prevent GPU resets, because resets are not exploitable security holes. WebGL can cause GPU resets already.

Firefox is on the hook to avoid security holes. This means that we must avoid UB in shaders, not that shaders need to actually terminate in a reasonable amount of time. This is why the transformations suggested in [#6572](https://github.com/gfx-rs/wgpu/issues/6528#issuecomment-2477277145) are not concerned with imposing any realistic limit on execution time, merely on ensuring that loops are bounded in principle.

**Comment by jimblandy** [comment]
> This could also allow long-running compute by saving and restoring shader state.

Please take a look through the [RDNA3.5 Instruction Set Architecture Reference Guide](https://gpuopen.com/amd-gpu-architecture-programming-documentation/). A single RDNA3.5 workgroup processor has four SIMD units, each of which may have up to 1536 vector registers, each of which holds 32 32-bit values. This means the register state alone for one workgroup processor is 4 * 1536 * 32 * 4 = 786kiB. In addition, each workgroup processor has 128kiB local data store (LDS). There may be up to 48 workgroup processors on a high-end AMD GPU.

So a "context switch" on an RDNA GPU entails saving (786kiB + 128kiB)/WGP * 48WGP = almost 43MiB of data, and then restoring another 43MiB from from the context you're switching to. This is why it's generally avoided.

I hear NVIDIA is worse.

**Comment by jimblandy** [comment]
I thought of another angle to this.

One of the reasons that [limiting loops with counters](https://github.com/gfx-rs/wgpu/issues/6528#issuecomment-2477277145) is appealing is that it doesn't interfere with loop unrolling, as shown in https://github.com/gfx-rs/wgpu/issues/6528#issuecomment-2477406932. Loop unrolling is very important to GPUs, even more than it is to CPUs.

But part of the reason the optimizer is able to remove the limiting counter is that it knows the counter's initial value is `0xffff` upon entry to the loop. If it can't be sure that the limiting counter is larger than the number of iterations it plans to unroll, it must assume the loop might be stopped before it completes them all.

In order to implement the timeout behavior, you would need to have a single counter shared by all loops in the shader, to ensure that the overall time consumed so far is accumulated over successive loops. This would mean that the optimizer could only remove the counter if it was able to put an upper bound on how many iterations all prior loops executed, and determine that the lowest possible counter value would still permit the number of iterations it wanted to unroll.

I wouldn't be surprised if an optimizer could do this in some simple cases, but I would be amazed if it could do it as reliably as it does when the counter is initialized immediately before each loop.

**Comment by cwfitzgerald** [comment]
Closing as out of scope
