### ISSUE TITLE
Intel MSAA Resolve + SRGB

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#725]
## Description

On intel/linux systems, there is a long standing issue with doing MSAA resolve at the same time as SRGB resolve will cause MSAA not to work and the clear color to not be properly converted into SRGB.

## Platform

Linux + Intel GPU

## What we do

- [ ] Verify this doesn't affect windows
- [ ] We need to warn when doing MSAA and SRGB on an intel chip on affected platforms.

**Comment by kvark** [comment]
gfx-rs has some internal logic to work around bugs, so in general we should first consider putting a workaround there. Perhaps what we should do for this issue is change [`image_format_properties`](https://github.com/gfx-rs/gfx/blob/b8727da4cb912625f146f6b3ecd8fb1ffa684614/src/backend/vulkan/src/lib.rs#L833) implementation on Vulkan to report the maximum MSAA count of 1 *only* for SRGB formats only on the affected platforms?

**Comment by cwfitzgerald** [comment]
I think we've fixed this.

**Comment by mockersf** [comment]
this seems to still happen in Bevy with wgpu 0.16
