### ISSUE TITLE
Builder patterns for descriptors

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#851]
**Is your feature request related to a problem? Please describe.**
Since the bovine intervention of #822, we now have a problem in wgpu-rs, since `Cow` is overly verbose.
Another problem is extending structures with extensions without breaking the API. We tried to roll it out previously, but then faced issues, and had to roll back in #787. With builders, the path to non-exhaustive is open.

**Describe the solution you'd like**
Follow the pattern established in #840 for other descriptors. This is done with help of our `IntoCow` trait.

**Describe alternatives you've considered**
Plain structures. Ends up overly verbose, and are hard to expand.

**Comment by Andful** [comment]
I am currently working on it. Hopefully will have a first draft of the builder functions soon.

**Comment by jprudil** [comment]
Would it be possible to use [derive_builder](https://docs.rs/derive_builder/0.9.0/derive_builder/)? It's a well-known crate and requires only a `#[derive(Builder)]` to get started, it also supports carrying over doc comments, intentionally leaving out some fields, custom traits etc. The current builder for `TextureDescriptor` already suffers from quite a lot of code duplication for something that could (potentially) be automated.

**Comment by Andful** [comment]
I do somewhat agree with @jprudil 's idea. I made a pull request with the work-in-progress changes. Not all the structs were given builder pattern but already an additional 500 lines of code is added to a file of 2000 lines of code. Most of the code is very repetitive.
Even though I agree that we should have an automated process to generate the builder implementation, I don't think derive_builder quite matches our use case for the following reasons:
* Not all fields should have a default value, but the user should explicitly pass values for variables with no trivial default value in the function `new`. In the example in #840, those are `size`, `dimension`, `format`, `usage`.
* In case the struct has a `label` field with a generic type `L`, we what to implement the builder pattern only for `L` being `Option<Cow<'a, str>>` (because that is the specialization used in `wgpu-rs`).
* Some setter functions that sets a `Cow` field should accept a `IntoCow` argument and call `into_cow` to set the field.

**Comment by jprudil** [comment]
To address your first concern (provided I understand it correctly): Default values are opt-in with derive_builder. If your member/struct implements the Default trait, you can specify `#[builder(default)]` to make it optional, you can also specify `#[builder(default = "expr")]` where expr is an arbitrary expression of compatible type for that specific member/struct. In case you don't provide defaults, calling the final build method will error out with a message saying what exactly is missing.

**Comment by kvark** [comment]
@jprudil would `derive_builder` support our `IntoCow` like in #840 ?

**Comment by cwfitzgerald** [comment]
The other limitations of the existing builder pattern derives is that they don't support grouping members together. For things that inherently go together, it makes sense to have a single builder method instead of many.

**Comment by jprudil** [comment]
@kvark I think it should one way or another. Can't check right now with a concrete example, but if you decided to go for `Into<Cow>` instead of `IntoCow` (as per information in https://github.com/gfx-rs/wgpu-rs/issues/478#issuecomment-663862638) then derive_builder should support the use case, [like this](https://docs.rs/derive_builder/0.9.0/derive_builder/#generic-setters).

**Comment by kvark** [comment]
@jprudil we went with `IntoCow` out of necessity, we can't have `Into<Cow>`, so it sounds like the derivation is not really an option for us.

**Comment by jprudil** [comment]
Well then, the only solution I can think of is:
1. Add `#[builder(setter(into))]` before every `Cow` member
2. Pass a vector/slice to the builder method for that member

That's still pretty undesirable from a usage perspective in the common case of passing a fixed number of elements in an array, because the user still has to add either `[..]` at the end or `vec!` at the start. Maybe there is a better, more elegant solution, but I don't see it, especially not in a single line of code, which I guess is the advantage of this approach.

**Comment by kvark** [comment]
Fixed by #856
